---
title: "Initial Exprolatory Data Analysis"
author:
- name: Elyas Heidari & Artem Lomakin
  affiliation: 
  - AI in Oncology, DKFZ Heidelberg
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: false
---

# Setup / definitions

## Libraries

```{r setup_knitr, include=FALSE}
library('BiocStyle')
options(bitmapType='cairo')
set.seed(1996)
knitr::opts_chunk$set( autodep=TRUE, cache=TRUE, cache.lazy=FALSE, dev='png' )
knitr::opts_knit$set( root.dir='..' )
# wflow_build(files='analysis/00_initial_eda.Rmd', view=F, verbose=T, delete_cache=T)
```

```{r setup_libs, collapse=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
suppressMessages(source('code/R/dep.R')) 
```

## Helper functions

```{r setup_helpers, message=FALSE, cache=TRUE}
suppressMessages(source('code/R/utils.R')) 
suppressMessages(source('code/R/analysis_constants.R')) 
library("spatialLIBD")
# source('code/R/sma01_eda.R')
```

## Paths

```{r setup_input}
tag       = '00_anndata_objects' 
# ref_tag   = 'embryo1_2'
data_raw_dir  = 'data_raw'
data_tidy_dir = 'data_tidy'
out_dir   =  file.path('output', tag)

decodes_dir = 'data_raw/decodes'
decodes_f   = list.files(decodes_dir, full.names=TRUE)
decodes_tags = decodes_f %>% 
    purrr::map(~str_replace(.x, pattern='data_raw/decodes/', replacement='')) %>% 
    purrr::map(~str_replace(.x, pattern='_DECODEv1.csv', replacement='')) %>% 
    unlist
names(decodes_f) = decodes_tags

nodules_anno_dir = 'data_raw/nodule_annotations_final'
nodules_anno_f   = list.files(nodules_anno_dir, full.names=TRUE)
nodules_anno_tags = nodules_anno_f %>% 
    purrr::map(~str_replace(.x, pattern='data_raw/nodule_annotations_final/', replacement='')) %>%
    purrr::map(~str_replace(.x, pattern='\\.csv', replacement='')) %>%
    unlist
names(nodules_anno_f) = nodules_anno_tags


samples_f     = list.dirs(data_raw_dir, recursive=FALSE) %>% str_subset('ML')
samples_tags  = samples_f %>% purrr::map(~str_replace(.x, pattern='data_raw/', replacement='')) %>% unlist
names(samples_f) = samples_tags

obj_dir  = file.path('objects', tag)
dir.create(obj_dir)
obj_list = list()
fig_dir  = file.path('output', tag)
dir.create(fig_dir)
fig_list = list()
```


## Load inputs

```{r load_inputs, fig.height=8, fig.width=8, results='asis', cache=TRUE}
adata = zellkonverter::readH5AD('data_tidy/joint_coexp_2024_02_29.h5ad')
# adata = adata[,colData(adata)$batch == 'ML_I']
counts(adata) = assays(adata)[['X']]
adata = adata[is.na(rowData(adata)$Plasmid),]
remove_empty_spots <- function(spe){
    spe = spe[,colSums(counts(spe)) != 0]
    spe = spe[rowSums(counts(spe)) != 0,]
    spe
}
adata = remove_empty_spots(adata)
adata = scuttle::logNormCounts(adata)
to_keep = rownames(rowData(adata) %>% .[.$tumor != 'NaN' | .$tme != 'NaN',])# |!is.na(.$Plasmid), ] ) # | .$sig !='NaN',

exprs = counts(adata) %>%
    t %>% 
    as.data.table
cor =    cov.wt(exprs , method='ML')$cov %>%
    cov2cor 
exprs = cor %>%
    glasso::glasso(rho=0.2) %>%
    .$wi 
rownames(exprs ) = colnames(exprs) =rownames(adata) 
exprs2 = exprs
cor2 = cor
exprs2[to_keep, to_keep] = exprs2[to_keep, to_keep] + ifelse( exprs2[to_keep, to_keep] > 0, .3, ifelse( exprs2[to_keep, to_keep] < 0, -.3, 0))
cor2[to_keep, to_keep] = cor2[to_keep, to_keep] + .1
# cor2[to_keep] = cor2[to_keep] * 2
exprs2 = abs(exprs2) * (cor2 > 0.25)
exprs_bin =  (exprs2 != 0)
diag(exprs_bin ) = F
rownames(exprs_bin ) = colnames(exprs_bin) =rownames(adata) #= to_keep
rownames(exprs2 ) = colnames(exprs2) =rownames(adata) # = to_keep
to_keep_expand =names(which(colSums(exprs_bin[to_keep,]) >0))
exprs_bin = exprs_bin[to_keep_expand, to_keep_expand]
to_keep = intersect(to_keep, rownames(exprs_bin))
exprs_bin = exprs_bin[rev(c(to_keep, setdiff(rownames(exprs_bin), to_keep))), rev(c(to_keep, setdiff(rownames(exprs_bin), to_keep)))]
edge_imp = rownames(rowData(adata) %>% .[(.$tumor != 'NaN' & .$tumor != 'tumor_add_on') | (.$tme != 'NaN' & .$tme != 'tme_add_on'),])
edge_imp = intersect(edge_imp, rownames(exprs_bin))
exprs_bin = exprs_bin[rev(c(edge_imp, rev(setdiff(rownames(exprs_bin), edge_imp)))), rev(c(edge_imp, rev(setdiff(rownames(exprs_bin), edge_imp))))]

exprs_graph = graph_from_adjacency_matrix(exprs_bin) %>%
    as.undirected %>%
    remove_isolated_nodes
# cons_graph = as.undirected(cons_graph)

gg = rowData(adata)[names(V(exprs_graph)),]
exprs_mem = ifelse(
    gg$tumor != 'NaN', as.character(gg$tumor), 
    ifelse(gg$tme != 'NaN', as.character(gg$tme), 'NaN')) 
        # ifelse(gg$pheno != 'NaN', as.character(gg$pheno), 
        #     ifelse(gg$sig != 'NaN', as.character(gg$sig), 
        #         ifelse(!is.na(gg$Plasmid), as.character(gg$Plasmid), 'NaN')))))
names(exprs_mem) = names(V(exprs_graph))
exprs_lay = layout_nicely(exprs_graph)
V(exprs_graph)$labels = names(exprs_mem)

celltype_cols_static = c(
#   'Mesenchymal'     = '',
  'Fibroblasts'     = '#ffff00',
  'Erythrocytes'    = '#de7812',
  'Kupffer cells'   = '#000075',
  'Neutrophils'     = '#7BAFDE',
  'Platelets'       = '#f9decf',
#   'NK cells'        = '#bbe30b',
  'B cells'         = '#4fe30b',
#   'T cells'         = '#4fe30b',
  'Mast cells'      = '#B51D8D',
#   'Endothelial'     = '#7BAFDE',
  'Periportal HCC'  = '#FACB12',
  'Pericentral HCC' = '#FF2F00',
  'Cholangiocytes'  = '#32a8a6',
  'Histone'         = "#DFCDE4",
  'tumor_add_on'          = '#9e6762',
  'tme_add_on'          = '#9e6762',
  'Other'   =   '#E7298A',
  'NaN' = '#D2EAF6'
)

to_keep = c(to_keep, 'Sox9')

pdf('output/test_coexp_graph_03_23_hvgs.pdf', height=50, width=50)
igraph::V(exprs_graph)$size = ifelse(names(V(exprs_graph)) %in% to_keep, 5, 2)
igraph::V(exprs_graph)$label.cex = ifelse(names(V(exprs_graph)) %in% to_keep, 2.5, 1)
igraph::V(exprs_graph)$frame.width = ifelse(names(V(exprs_graph)) %in% to_keep, 5, 0)
igraph::V(exprs_graph)$frame.color = ifelse(names(V(exprs_graph)) %in% to_keep, 'black', 0)
E(exprs_graph)$color = ifelse((exprs_mem[tail_of(exprs_graph, E(exprs_graph))] == exprs_mem[head_of(exprs_graph, E(exprs_graph))]) & names(tail_of(exprs_graph, E(exprs_graph))) %in% edge_imp, celltype_cols_static[exprs_mem[head_of(exprs_graph, E(exprs_graph))]], '#C1BFBF')
E(exprs_graph)$width = ifelse((exprs_mem[tail_of(exprs_graph, E(exprs_graph))] == exprs_mem[head_of(exprs_graph, E(exprs_graph))]) & names(tail_of(exprs_graph, E(exprs_graph))) %in% edge_imp, 25, 1)
# E(exprs_graph)$edge.color = 'black'
# rownames(exprs_lay) = names(V(exprs_graph))
# V(exprs_graph) = c(edge_imp, setdiff(names(V(exprs_graph)), edge_imp))
# exprs_lay = exprs_lay[names(V(exprs_graph)), ]
gg = graph_col_comm(
    graph  = exprs_graph, 
    lay    = exprs_lay * 2, 
    # sz = ,
    # grp    = colorjam::rainbowJam(length(unique(exprs_mem)))[as.numeric(as.factor(exprs_mem))], 
    grp    = celltype_cols_static[exprs_mem],
    title  = 'Gene Interaction Netwrok on Markers and Highly Variable Genes', 
    labels = names(exprs_mem)
)
print(gg)
dev.off()

```


```{r session_info, include=TRUE, echo=TRUE, results='markup'}
devtools::session_info()
```
