---
title: "Initial Exprolatory Data Analysis"
author:
- name: Elyas Heidari & Artem Lomakin
  affiliation: 
  - AI in Oncology, DKFZ Heidelberg
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: false
---

# Setup / definitions

## Libraries

```{r setup_knitr, include=FALSE}
library('BiocStyle')
options(bitmapType='cairo')
set.seed(1996)
knitr::opts_chunk$set( autodep=TRUE, cache=TRUE, cache.lazy=FALSE, dev='png' )
knitr::opts_knit$set( root.dir='..' )
# wflow_build(files='analysis/00_initial_eda.Rmd', view=F, verbose=T, delete_cache=T)
```

```{r setup_libs, collapse=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
suppressMessages(source('code/R/dep.R')) 
```

## Helper functions

```{r setup_helpers, message=FALSE, cache=TRUE}
# suppressMessages(source('code/R/utils.R')) 
# suppressMessages(source('code/R/analysis_constants.R')) 
# library("spatialLIBD")

suppressMessages(source('code/R/utils.R')) 
suppressMessages(source('code/R/analysis_constants.R')) 
library("spatialLIBD")
library(anndata)
library(viridis)
library(ComplexHeatmap)
library(tidyverse)
library(zellkonverter)
library(dendsort)
# source('code/R/sma01_eda.R')
```

## Paths

```{r setup_input}
tag       = 'composed_anndata_objects_2023_12_13' 
# /Users/b450-admin/Desktop/Projects/elyas_proj/new_projects_2023/perturb_cast_2023/data_tidy/geno_pheno_objs_2023_12_05
# ref_tag   = 'embryo1_2'
data_tidy_dir = 'data_tidy'
out_dir   =  file.path('output', tag)

adata_dir = file.path(data_tidy_dir, tag)

adata_f   = list.files(adata_dir, full.names=TRUE) 
# adata_f[grep('\\.h5ad', adata_f)] %>% map(~Convert(.x, "h5seurat", overwrite=T))
adata_f  = list.files(adata_dir, full.names=TRUE) %>% .[grep('\\.h5ad', .)]

adata_tags = adata_f %>% 
    purrr::map(~str_replace(.x, pattern=adata_dir, replacement='')) %>%
    purrr::map(~str_replace(.x, pattern='\\.h5ad', replacement='')) %>%
    purrr::map(~str_replace(.x, pattern='/geno_pheno_', replacement='')) %>%
    unlist
names(adata_f) = adata_tags

obj_dir  = file.path('objects', tag)
dir.create(obj_dir)
obj_list = list()
fig_dir  = file.path('output', tag)
dir.create(fig_dir)
fig_list = list()
```


## Load inputs

```{r load_inputs, fig.height=8, fig.width=8, results='asis', cache=TRUE}
library(anndata)
adata = anndata::read_h5ad('data_tidy/new_geno_nodule_2024_01_30.h5ad')
#reticulate::install_miniconda()

library(circlize)
col_fun = colorRamp2(c(0, 1), c("white", "black"))


# B cell —> B cell
# erythroblast —> erythroblast
# fibroblast —> fibroblast
# kupffer cell/macrophage —> kupffer cell/macrophage
# mast cell —> mast cell
# neutrophil —> neutrophil
# platelet —> platelet
# histone-enriched —> histone-enriched-enriched
# Midlobular/Hamp2/Upp2-enriched —> Hamp2/Upp2-enriched
# central —> central
# portal —> portal

plasmids = c(
    'MYC',
    'NICD',
    'coVEGFA',
    'mtCtnnb1',
    'shMLL3',
    'shPTEN',
    'shRen',
    'shtrp53'
)

names(plasmids) = plasmids
plasmid_cols = c(
    'MYC.plasmid'      = colorRamp2(c(0, 1), c("white", "#56B4E9")),
    'NICD.plasmid'     = colorRamp2(c(0, 1), c("white", "#E69F00")),
    'coVEGFA.plasmid'  = colorRamp2(c(0, 1), c("white", "#CC79A7")),
    'mtCtnnb1' = colorRamp2(c(0, 1), c("white", "black")),
    'shMLL3.plasmid'   = colorRamp2(c(0, 1), c("white", "#0072B2")),
    'shPTEN.plasmid'   = colorRamp2(c(0, 1), c("white", "#009E73")),
    'shRen.plasmid'    = colorRamp2(c(0, 1), c("white", "#F0E442")),
    'shtrp53.plasmid'  = colorRamp2(c(0, 1), c("white", "#D55E00"))
)

plasmid_cols_stat = c(
    'MYC.plasmid'      = "#56B4E9",
    'NICD.plasmid'     = "#E69F00",
    'coVEGFA.plasmid'  = "#CC79A7",
    'mtCtnnb1' = "black",
    'shMLL3.plasmid'   = "#0072B2",
    'shPTEN.plasmid'   = "#009E73",
    'shRen.plasmid'    = "#F0E442",
    'shtrp53.plasmid'  = "#D55E00"
)
bl_red = colorRamp2(c(0, 1), c("white", "red"))


plasmid_order = c(
    'MYC-plasmid',
    'mtCtnnb1',
    'coVEGFA-plasmid',
    'shMLL3-plasmid',
    'NICD-plasmid',
    'shRen-plasmid',
    'shtrp53-plasmid',
    'shPTEN-plasmid')


celltype_cols_static = c(
#   'Mesenchymal'     = '',
  'fibroblast'     = '#ffff00',
  'erythroblast'    = '#de7812',
  'kupffer cell/macrophage'   = '#000075',
  'neutrophil'     = '#7BAFDE',
  'platelet'       = '#f9decf',
#   'NK cells'        = '#bbe30b',
  'B cell'         = '#4fe30b',
#   'T cells'         = '#4fe30b',
  'mast cell'      = '#B51D8D',
#   'Endothelial'     = '#7BAFDE',
  'portal'  = '#FACB12',
  'central' = '#FF2F00',
  'cholangiocytic'  = '#32a8a6',
  'histone-enriched'         = "#DFCDE4",
  'tumor_add_on'          = 'white',
  'tme_add_on'          = 'white',
  'Hamp2/Upp2-enriched'   =   '#E7298A',
  'NaN' = 'white'
)

tumor_genes_order = rev(c('cholangiocytic', 'portal', 'central', 'Hamp2/Upp2-enriched', 'histone-enriched', 'tumor_add_on'))
tme_genes_order = c('fibroblast', 'erythroblast', 'mast cell', 'neutrophil', 'platelet', 'B cell', 'kupffer cell/macrophage', 'tme_add_on')
tumor_order =rev(c('cholangiocytic', 'portal', 'central', 'Hamp2/Upp2-enriched', 'histone-enriched', 'Unclassified', 'Normal'))# , 'add_on' ))
tme_order = c('fibroblast', 'erythroblast', 'mast cell', 'neutrophil', 'platelet', 'B cell', 'kupffer cell/macrophage')#, 'add_on') 
tme_colors = c(
        'Mesenchymal'    = colorRamp2(c(0, 1), c("white", '#FF2F00')),
        'fibroblast_bin'    = colorRamp2(c(0, 1), c("white", '#ffff00')),
        'erythroblast_bin'   = colorRamp2(c(0, 1), c("white", '#de7812')),
        'kupffer cell/macrophage_bin'  = colorRamp2(c(0, 1), c("white", '#000075')),
        'neutrophil_bin'    = colorRamp2(c(0, 1), c("white", '#7BAFDE')),
        'platelet_bin'      = colorRamp2(c(0, 1), c("white", '#f9decf')),
        'NK cells_bin'       = colorRamp2(c(0, 1), c("white", '#bbe30b')),
        'B cell_bin'        = colorRamp2(c(0, 1), c("white", '#4fe30b')),
        'T cells_bin'        = colorRamp2(c(0, 1), c("white", '#4fe30b')),
        # 'Monocytes'      = colorRamp2(c(0, 1), c("white", '#73db46')),
        'mast cell_bin'     = colorRamp2(c(0, 1), c("white", '#B51D8D'))
        # 'Endothelial'    = colorRamp2(c(0, 1), c("white", '#7BAFDE'))
)



tumor_colors = c(
        'portal_bin' = colorRamp2(c(0, 1), c("white", '#FACB12')),
        'central_bin'= colorRamp2(c(0, 1), c("white", '#FF2F00')),
        'cholangiocytic_bin' = colorRamp2(c(0, 1), c("white", '#32a8a6')),
        'histone-enriched_bin' = colorRamp2(c(0, 1), c("white", "#DFCDE4")),
        'Hamp2/Upp2-enriched_bin' = colorRamp2(c(0, 1), c("white", '#E7298A'))
)

abv_types = c(

  'fibroblast'     = 'Fibro.',
  'erythroblast'    = 'Erythro.',
  'kupffer cell/macrophage'   = 'Kupf.',
  'neutrophil'     = 'Neut.',
  'platelet'       = 'Plat.',
  'B cell'         = 'B',
  'mast cell'      = 'Mast',
'cholangiocytic'  = 'chol.',
  'portal'  = 'portal',
  'central' = 'central',
  'Hamp2/Upp2-enriched'   =   'Hamp2+/Upp2+',
  'histone-enriched'         = 'histone+',
  'Unclassified' = 'unclassified',
  'Normal' = 'non-tumor'
)

# plasmid_cols = plasmids %>% map(function(x) col_fun)
# plasmid_cols = append(plasmid_cols, list('expected_number'= 'red'))
```

## Separated heatmaps{.tabset}
```{r draw_hm_sep, fig.height=40, fig.width=40, results='asis', cache=TRUE}
regions = c('inside', 'core', 'edge', 'closure')
regions %>% map(~dir.create(sprintf('output/g2p_heatmaps_2024_02_01_v2/%s', .x), recursive = TRUE))

adata = anndata::read_h5ad('data_tidy/new_geno_nodule_2024_02_01.h5ad')
adata$var$tme_tumor = ifelse(adata$var$tme != 'NaN', adata$var$tme, ifelse(adata$var$tumor != 'NaN', adata$var$tumor, 'NaN'))
adata$layers[['inside']] = adata$X
for(region in regions){
    # adata$layers[[region]] = t(apply(t(adata$layers[[region]]), 2, function(x) (x)/(sum(x))))
    # adata$layers[[region]][is.nan(adata$layers[[region]])] <- 0
    for(p in unique(adata$var$tme_tumor)){
        if(p != 'NaN'){
            
            adata_sub = adata[,adata$var$tme_tumor == p]
            m  = t(adata_sub$layers[[region]])
            # m  = m[adata_sub$var$pheno == p,]
            # to_keep = colSums(m) > quantile(colSums(m), 0.1)
            # m = m[,to_keep]
            if(dim(adata_sub)[2] <= 1){
                next

            }
            # m  = apply(m, 2, function(x) (x)/(sum(x)))
            # m[is.nan(m)] <- 0
            # m  = t(apply(m, 1, function(x) ((x)/(max(x)))))
            # m[is.nan(m)] <- 0
            m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, 0.9), 1, ifelse(x < quantile(x, .1), 0, (x - quantile(x, .1)) / (quantile(x, 0.9) - quantile(x, .1))))))
            m[is.nan(m)] <- 0
            # if(sum(adata_sub$var$core != 'F') > 1)
            #     seriate_obj  = seriate(as.matrix(m[adata_sub$var$core != 'F', ])) #, method = "BEA_TSP")
            # else
            #     seriate_obj  = seriate(as.matrix(m)) # , method = "BEA_TSP")
            # column_order = get_order(seriate_obj, 2)
            # seriate_obj  = seriate(as.matrix(m))
            # row_order    = get_order(seriate_obj, 1)
            # adata_sub = adata_sub[to_keep,]
            plasmid_mask = data.frame((adata_sub$obsm$plasmid_mask))
            # colnames(plasmid_mask) = plasmids
            # plasmid_mask = plasmid_mask[,to_keep]
            stain_df     = adata_sub$obs[,grep(paste0('^',region), colnames(adata_sub$obs))]
            ccc_sds_df   = adata_sub$obs[,c('CCC_score', 'SDS_score')]
            ccc_sds_cr   = colorRamp2(c(0, 1), c("white", "blue"))
            ccc_sds_cols = ccc_sds_df %>% map(function(x) ccc_sds_cr)
            # ha_df      = cbind(ccc_sds_df^5, stain_df, plasmid_mask^5)
            ha_df = plasmid_mask^5
            stain_cr   = colorRamp2(c(0, 1), c("white", "green"))
            stain_cols = stain_df %>% map(function(x) stain_cr)
            # ha_cols    = append(append(plasmid_cols, stain_cols), ccc_sds_cols)
            # ha_cols    = append(plasmid_cols, ccc_sds_cols)
            ha_cols = plasmid_cols
            grp_vals     = seq(min(m), max(m), length.out=9)
            # grp_cols     = circlize::colorRamp2(c(min(m), median(m), max(m)), c("blue", "white", "red"))
            grp_cols     = circlize::colorRamp2(c(quantile(m, .1), max(1, quantile(m, 0.9))), c("#00bfff", "#A10037"))
            column_order = order(colSums(m))
            ha         = HeatmapAnnotation(
                df = ha_df, 
                col=ha_cols, 
                show_legend=FALSE, 
                gp = gpar(fontsize = 100), 
                height = unit(20, "cm"), 
                annotation_name_gp= gpar(fontsize = 40), 
                annotation_height = unit(10, "cm"), 
                simple_anno_size = unit(1.5, "cm")
            )
            gg = Heatmap(
                m, 
                # row_split=ifelse(adata_sub$var$core != 'F', 'Core', 'Hamp2/Upp2-enricheds'), 
                # cluster_rows = row_dend, 
                # cluster_columns = col_dend,
                # row_order=row_order, 
                column_order=column_order, 
                row_title_gp=gpar(fontsize = 100),
                row_names_gp=gpar(fontsize = 35),
                column_names_gp=gpar(fontsize = 40),
                name="Scaled\nGene Expression", 
                column_title = region,  
                column_title_gp = gpar(fontsize = 100, fontface = "bold"), 
                top_annotation = ha, 
                col = grp_cols
            )  # + row_annot
            p = str_replace_all(p, '/', '_')
            p = str_replace_all(p, ' ', '_')
            pdf(sprintf('output/g2p_heatmaps_2024_02_01/%s/%s.pdf', region, p), height=10+ifelse(dim(m)[1] < 4, 3 *dim(m)[1], ifelse(dim(m)[1] < 5, 2.5 *dim(m)[1], 1.75*dim(m)[1])), width=5+.75*dim(m)[2])
                draw(gg, padding = unit(c(150, 150, 20, 50), "mm"), show_heatmap_legend = FALSE)
            dev.off()
        }
    }
}


gene_inc = intersect(c("Clec4f", "Igkc", "Tpsb2", "Abcc3", "Tdo2", "Cma1", "Marco", "Ptgs1", "Sds", "Mup3", 
           "Akr1c6", "Serping1", "Mcpt4", "Tmcc2", "Apoc3", "Krt19", "Dpt", "Col3a1", "Cbr3", 
           "Cyp2f2", "Slc22a1", "Ugt3a2", "Sdc3", "Pltp", "Ccl6", "Ppbp", "Cyp2c29", "C1qc", 
           "Sod3", "S100a8", "Mpo", "Cyp1a2", "Hal", "Emb", "Ctss", "Ctsc", "Gstm1", "Igfbp7", 
           "Vsig4", "Gp2", "Irf7", "Cfh", "Slc16a7", "Mrc1", "Oat", "Aldh1a1", "Nr1i3", "Uroc1", 
           "Akr1c20", "Epas1", "Csf1r", "Clic6", "Slco1b2", "Maf", "Igf1", "Gjb2", "Ltf", "Sord", 
           "Cyp4a10", "Cd163", "Cyp4a14", "Ehd3", "Wfdc17", "Tspan8", "Cldn7", "Stab1", "Serbp1", 
           "Serpina3k", "Pck1", "Ngp", "Ckmt1", "Fcgr2b", "Alas2", "Elane", "Aqp1", "Ano9", "Etnppl", 
           "Colec10", "Pf4", "Cyp2e1", "Cldn1", "Krt7", "Sdsl", "Slc4a1", "Slc10a1", "Esrp1", "Fabp7", 
           "Pon1", "Fcna", "Arg1", "Gstm3", "Plet1", "Spint1", "Ehf", "Itga2b", "Ang", "Gstm2", "Plvap", 
           "Hbb-bt", "Gulo", "Ctsg", "Col1a1", "Slco2a1", "S100a9", "Bdh2", "Lect2", "Clec4g", "C6", 
           "Jchain", "Cdo1", "Slc40a1", "C1qb", "Lrg1", "F5", "Mapk13", "Car9", "Cd59a", "Cd5l", "Rgn", 
           "Slc15a2", "Colec11", "Ces1f", "Orm1", "Umod", "Hrg", "Tpsab1", "Ppp1r1b", "H2-D1", "Tmem268", 
           "Camp", "Tff2", "Nat8f2", "BC028528", "Serpina3n", "Dcn", "Cfp", "Bmyc", "Apcs", "Lhpp", "Wfdc21", 
           "Pigr", "St3gal5", "Baat", "Syt7", "Col5a1", "Aqp9", "Elf3", "Rdh16", "Ecm1", "Cyp2a4", "Kcnk1", 
           "C9", "Cyp2d26", "C1qa", "Epcam", "Cyp2c23", "Cpa3", "Gdf2", 'Thbs1', 'Gas6', 'Spp1', 'Sox9', 'Hist2h2bb', 
           'Hist1h3d', 'Hist1h2ag', 'Hist1h1c', 'Hist1h1e', 'Hist1h2bk', 'Hist1h4h', 'Hist4h4', 'Hist1h3c'), colnames(adata))
# genes = list()
# for(adata_tag in adata_tags){
#     assays(adata_list[[adata_tag]])[['inside']] = assays(adata_list[[adata_tag]])[['X']]
#     genes[[adata_tag]] = rownames(adata_list[[adata_tag]])
# }

# genes          = genes %>% purrr::reduce(intersect)
mtx            = list()
probs          = list()
ccc_sds_scores = list()
library(seriation)
pdf('output/hm_g2p_total_nodules_global_2024_02_29.pdf', width =30, height=40)
for(region in c('inside')){
    adata = anndata::read_h5ad('data_tidy/new_geno_nodule_2024_02_28.h5ad')
    adata$var$tme_tumor = ifelse(adata$var$tme != 'NaN', adata$var$tme, ifelse(adata$var$tumor != 'NaN', adata$var$tumor, 'NaN'))
    adata$layers[['inside']] = adata$X
    core_genes = adata$var_names[adata$var$tme_tumor != 'NaN']
    # adata$layers[[region]] = t(apply(t(adata$layers[[region]]), 2, function(x) (x)/(sum(x))))
    # adata$layers[[region]][is.nan(adata$layers[[region]])] <- 0
    m  = t(adata$layers[[region]])
    # m  = m[gene_inc,]
    # m  = 
    # adata = adata[colSums(m) > quantile(colSums(m), 0.2),]
    # m  = t(adata$layers[[region]])
    # # m = m[,colSums(m) > 500]
    # m  = m[adata$var$tme_tumor != 'NaN',]
    # mtx[[region]][[adata_tag]] = m
    # m  = apply(m, 2, function(x) (x)/(sum(x)))
    # m[is.nan(m)] <- 0
    # m = t(t(m)/colData(ad)$expected_number)
    # m  = t(apply(m, 1, function(x) ((x)/(max(x)))))
    m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, 0.95), 1, ifelse(x < quantile(x, 0.25), 0, (x - quantile(x, 0.25)) / (quantile(x, 0.95) - quantile(x, 0.25))))))
    m[is.nan(m)] <- 0

    grp_vals     = seq(0, 1, length.out=20)
    grp_cols     = circlize::colorRamp2(grp_vals, pals::ocean.thermal(20))
    # grp_cols     = circlize::colorRamp2(c(quantile(m, 0.35), quantile(m, 0.45), quantile(m, 0.95)), c("#00bfff", "white", "#A10037"))
    stain_df     = adata$obs[,grep(paste0('^',region), colnames(adata$obs))]
    ccc_sds_df   = adata$obs[,c('CCC_score', 'SDS_score')]
    ccc_sds_cr   = colorRamp2(c(0, 1), c("white", "blue"))
    ccc_sds_cols = ccc_sds_df %>% map(function(x) ccc_sds_cr)
    plasmid_mask = data.frame((adata$obsm$plasmid_mask))
    # ccc_sds_scores[[region]][[adata_tag]] = as.matrix(adata$obs[,c('CCC_score', 'SDS_score')]) * adata$obs$expected_number
    # ha_df      = cbind(ccc_sds_df^5, stain_df, plasmid_mask^5)
    ha_df      = cbind(plasmid_mask^5)
    stain_cr   = colorRamp2(c(0, 1), c("white", "green"))
    stain_cols = stain_df %>% map(function(x) stain_cr)
    # ha_cols    = append(append(plasmid_cols, stain_cols), ccc_sds_cols)
    ha_cols = plasmid_cols
    ha         = HeatmapAnnotation(df = ha_df[colSums(m) != 0,], col=ha_cols, show_legend=FALSE, gp = gpar(fontsize = 100), height = unit(5, "cm"), annotation_name_gp= gpar(fontsize = 10), annotation_height = unit(5, "cm"), simple_anno_size = unit(.25, "cm"))
    # row_ha = rowAnnotation(foo = anno_mark(at = (1:dim(m)[1])[rownames(m) %in% adata$var_names[adata$var$sel == 'T']], labels =rownames(m)[rownames(m) %in% adata$var_names[adata$var$sel == 'T']], labels_gp = gpar(fontsize = 15)))
    # row_annot  = Heatmap(
    #     # adata$varm$sig_mask, 
    #     adata[,adata$var$tme_tumor != 'NaN']$varm$sig_mask, 
    #     column_names_gp=gpar(fontsize = 30), 
    #     row_names_gp=gpar(fontsize =30),
    #     # right_annotation = row_ha,
    #     # show_row_names = FALSE,
    #     # row_names_gp=gpar(fontsize = ifelse(rownames(m) %in% adata$var_names[adata$var$sel == 'T'], 50, 0)), 
    #     name = "mat1", width = unit(20, "cm"), cluster_columns = FALSE, col=bl_red
    # )
    # ra = Heatmap(adata$var[adata$var$tme_tumor != 'NaN',]['tme_tumor'], name='celltypes', width = unit(2, "cm"), col= celltype_cols, show_legend= c(df=FALSE), simple_anno_size = unit(1.5, "cm"))

    # pdf(sprintf('output/%s_%s_hm_g2p.pdf', region, adata_tag), width =40, height=40)
    m[is.nan(m)] <- 0
    # column_order = column_order[colnames(m)]
    m = m[,colSums(m) != 0 ]
    # split=factor(ifelse(adata$var[gene_inc,]['tme'] != 'NaN', 'TME', 'Tumor'), levels=c('Tumor', 'TME'))[rowSums(m) != 0]

    m = m[rowSums(m) != 0, ]
    # row_ha = rowAnnotation(foo = anno_mark(at = (1:dim(m)[1])[rownames(m) %in% adata$var_names[adata$var$tme_tumor != 'NaN']], labels =rownames(m)[rownames(m) %in% adata$var_names[adata$var$tme_tumor != 'NaN']], labels_gp = gpar(fontsize = 5)))
    # ra = Heatmap(adata$var[gene_inc,][rowSums(m) != 0,]['tme_tumor'], name='signature', 
    #         width = unit(.5, "cm"), col= celltype_cols, 
    #         right_annotation = row_ha, show_row_names = FALSE,
    #         row_names_gp=gpar(fontsize =5),column_names_gp=gpar(fontsize = 0),
    #     )
    # seriate_obj  = seriate(as.matrix(m[rownames(m) %in% adata$var_names[adata$var$tme != 'NaN'],]), method = "PCA")
    # seriate_obj  = seriate(as.matrix(m), method = "BEA_TSP")
    # row_order    = get_order(seriate_obj, 1)
    # column_order = get_order(seriate_obj, 2)
    # split = cutree(hclust(as.dist(1- cor(t(m^2), method='pearson'))), k = 10)
    # split = cutree(hclust(as.dist(1- cor(t(m), method='spearman'))), k = 15)
    # split = cutree(hclust(dist(m^2)), k = 15)
    # split = split[names(sort(row_order))]
    text_split = unique(split) %>% map(~paste(names(split[split == .x]), collapse=', '))
    # text_split = unique(split) %>% map(~names(split[split == .x]))
    names(text_split) = unique(split)
    col_dend = as.dendrogram(hclust(as.dist(1- cor(m[rownames(m) %in% core_genes,], method='spearman'))))
    row_ha = rowAnnotation(foo = anno_mark(at = (1:dim(m)[1])[rownames(m) %in% core_genes], labels =rownames(m)[rownames(m) %in% core_genes], labels_gp = gpar(fontsize = 10)))
    column_order = order(factor(adata[colnames(m),]$obs[,'dom_type'], ordered=TRUE, levels = c(tumor_order, 'add_on')))
    col_split =  factor(adata[colnames(m),]$obs[,'dom_tumor'], ordered=TRUE, levels = tumor_order)
    col_split = ifelse(col_split == 'Normal', 'Normal', 'Tumor')
    gg = Heatmap(m^2, 
        # row_split=10, 
        column_split=col_split,
        # row_names_gp=gpar(fontsize = 40),
        # row_order=row_order,
        # column_order=column_order, 
        # clustering_distance_rows = "pearson",
        # clustering_distance_columns = 'pearson' ,
        right_annotation = row_ha,
        # right_annotation = rowAnnotation(
        #     textbox = anno_textbox(split, text_split, gp = gpar(fontsize = 10, col = "black"), 
        #     max_width = unit(20, "cm"), background_gp = gpar(fill = "white", col = '#666666'), 
        #     side = "right", word_wrap=TRUE)#, by = "anno_block")
        # ),
        # row_names_gp=gpar(fontsize = ifelse(rownames(m) %in% core_genes, 7.5, 1)),
        rect_gp = gpar(col = NA, lwd = 0), 
        row_title_gp = gpar(fontsize = 0),
        # row_dend_reorder = TRUE,
        column_dend_reorder = FALSE,
        # cluster_columns = col_dend,
        # right_annotation = ra,
        # show_column_dend = FALSE,
        # show_row_dend = FALSE,
        clustering_distance_rows = 'spearman',
        cluster_column_slices = FALSE,
        # clustering_method_rows = "spearman",
        # cluster_columns=col_dend,
        # clustering_method_columns = "spearman",
        # clustering_distance_columns = 'spearman',
        # clustering_distance_columns = function(x, y) 1 - cor(x[intersect(rownames(m), core_genes)], y[intersect(rownames(m), core_genes)], method='spearman') ,
        # clustering_distance_rows = function(x, y) 1- (sum(x[intersect(rownames(m), core_genes)] * y[intersect(rownames(m), core_genes)]))/(norm(x[intersect(rownames(m), core_genes)]) * norm(y[intersect(rownames(m), core_genes)])),
        row_names_gp=gpar(fontsize = 5),
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        row_gap = unit(.5, "mm"),
        # cluster_row_slices = FALSE,
        # column_title_gp=gpar(fontsize = 10),
        show_row_names =FALSE,
        column_names_gp=gpar(fontsize = 0),
        name="Scaled\nGene Expression", column_title = '',  column_title_gp = gpar(fontsize = 20, fontface = "bold"), top_annotation =ha, col=grp_cols) # + ra
    draw(gg, padding = unit(c(50, 50, 10, 25), "mm"), show_heatmap_legend = FALSE)
    # dev.off()
        # cat('\n\n')
    }
dev.off()



```


## Separated heatmaps{.tabset}
```{r draw_hm_sep, fig.height=40, fig.width=40, results='asis', cache=TRUE}
multi_df = rbind(m, t(plasmid_mask[colnames(m),]))[c(rownames(m)[rownames(m) %in% adata$var_names[adata$var$tme_tumor != 'NaN']], names(plasmid_cols)),]

exprs = multi_df %>%
    t %>% 
    as.data.table
cor =    cov.wt(exprs , method='ML')$cov %>%
    cov2cor 
exprs = cor %>%
    glasso::glasso(rho=0.1) %>%
    .$wi 
rownames(exprs ) = colnames(exprs) =rownames(multi_df)
# exprs2 = abs(exprs) * cor
rownames(exprs2 ) = colnames(exprs2) =rownames(multi_df)

# cor = cor(exprs, method='kendall')
exprs2 = (abs(cor) > .2) * cor
exprs2[rownames(m)[rownames(m) %in% adata$var_names[adata$var$tme_tumor != 'NaN']], rownames(m)[rownames(m) %in% adata$var_names[adata$var$tme_tumor != 'NaN']]] = 0
exprs2[colnames(plasmid_mask), colnames(plasmid_mask)] = 0
cor2 = cor
# exprs2[to_keep, to_keep] = exprs2[to_keep, to_keep] + ifelse( exprs2[to_keep, to_keep] > 0, .2, -.2)
# cor2[to_keep, to_keep] = cor2[to_keep, to_keep] + .1
# cor2[to_keep] = cor2[to_keep] * 2
# exprs2 = abs(exprs2) * (cor2 > 0.5)
# exprs2 = (cor2 > 0.9)
# exprs2 = cor(exprs, method='spearman')
exprs_bin =  (abs(exprs2) > 0)
diag(exprs_bin ) = F
# rownames(exprs_bin ) = colnames(exprs_bin) =rownames(adata) #= to_keep
# rownames(exprs2 ) = colnames(exprs2) =rownames(adata) # = to_keep
# to_keep_expand =names(which(colSums(exprs_bin[to_keep,]) >0))
# exprs_bin = exprs_bin[to_keep_expand, to_keep_expand]
diag(exprs2) = 0
exprs_graph = graph_from_adjacency_matrix(exprs2, weighted=TRUE) %>%
    as.undirected %>%
    remove_isolated_nodes
# cons_graph = as.undirected(cons_graph)

gg = names(V(exprs_graph))
exprs_mem = ifelse(gg %in% rownames(m),adata$var['tme_tumor'][gg,], gg)
celltype_numeric = as.numeric(factor(exprs_mem[gg %in% rownames(m)]))
plasmid_numeric = as.numeric(factor(exprs_mem[!(gg %in% rownames(m))]))
names(exprs_mem) = names(V(exprs_graph))
exprs_lay = layout_nicely(exprs_graph)
pdf('output/test_multi_graph.pdf', height=15, width=10)
g = graph_col_comm(
    graph  = exprs_graph, 
    # lay    = cbind(ifelse(gg %in% rownames(m), exprs_lay[,1], mean(exprs_lay[,1]) + 10), exprs_lay[,2]),
    lay    = cbind(ifelse(gg %in% rownames(m), 1, 3), ifelse(gg %in% rownames(m), (celltype_numeric-1) * 50 + runif(length(celltype_numeric), -25,25), (plasmid_numeric-1) * 50 + 50)),
    # lay    = cbind(ifelse(gg %in% rownames(m), 1, 10), ifelse(gg %in% rownames(m), ((1:length(celltype_numeric))*10)[order(celltype_numeric)], (plasmid_numeric) * 50)),
    sz     = ifelse(gg %in% rownames(m), 5, 15),
    grp    = c(celltype_cols, plasmid_cols_stat)[exprs_mem], 
    title  = 'exprsensus graph on all slides', 
    labels = names(exprs_mem)
)
print(g)
dev.off()
```


## Separated heatmaps{.tabset}
```{r draw_hm_sep, fig.height=40, fig.width=40, results='asis', cache=TRUE}

# genes          = genes %>% purrr::reduce(intersect)
mtx            = list()
probs          = list()
ccc_sds_scores = list()
library(seriation)
pdf('output/hm_g2p_total_nodules_global_2024_02_13.pdf', width =15, height=10)
for(region in regions[1]){
    adata = anndata::read_h5ad('data_tidy/new_geno_nodule_2024_02_19.h5ad')
    adata$var$tme_tumor = ifelse(adata$var$tme != 'NaN', adata$var$tme, ifelse(adata$var$tumor != 'NaN', adata$var$tumor, 'NaN'))
    adata$layers[['inside']] = adata$X
    # adata$layers[[region]] = t(apply(t(adata$layers[[region]]), 2, function(x) (x)/(sum(x))))
    # adata$layers[[region]][is.nan(adata$layers[[region]])] <- 0
    m  = t(adata$layers[[region]])
    m  = m[gene_inc,]
    # m  = 
    # adata = adata[colSums(m) > quantile(colSums(m), 0.2),]
    # m  = t(adata$layers[[region]])
    # # m = m[,colSums(m) > 500]
    # m  = m[adata$var$tme_tumor != 'NaN',]
    # mtx[[region]][[adata_tag]] = m
    # m  = apply(m, 2, function(x) (x)/(sum(x)))
    # m[is.nan(m)] <- 0
    # m = t(t(m)/colData(ad)$expected_number)
    # m  = t(apply(m, 1, function(x) ((x)/(max(x)))))
    m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, 0.99), 1, ifelse(x < quantile(x, 0.25), 0, (x - quantile(x, 0.25)) / (quantile(x, 0.99) - quantile(x, 0.25))))))
    m[is.nan(m)] <- 0

    grp_vals     = seq(0, 1, length.out=15)
    grp_cols     = circlize::colorRamp2(grp_vals, pals::ocean.thermal(15))
    # grp_cols     = circlize::colorRamp2(c(quantile(m, 0.35), quantile(m, 0.45), quantile(m, 0.95)), c("#00bfff", "white", "#A10037"))
    stain_df     = adata$obs[,grep(paste0('^',region), colnames(adata$obs))]
    ccc_sds_df   = adata$obs[,c('CCC_score', 'SDS_score')]
    ccc_sds_cr   = colorRamp2(c(0, 1), c("white", "blue"))
    ccc_sds_cols = ccc_sds_df %>% map(function(x) ccc_sds_cr)
    plasmid_mask = data.frame((adata$obsm$plasmid_mask))
    # ccc_sds_scores[[region]][[adata_tag]] = as.matrix(adata$obs[,c('CCC_score', 'SDS_score')]) * adata$obs$expected_number
    # ha_df      = cbind(ccc_sds_df^5, stain_df, plasmid_mask^5)

    stain_cr   = colorRamp2(c(0, 1), c("white", "green"))
    stain_cols = stain_df %>% map(function(x) stain_cr)
    # ha_cols    = append(append(plasmid_cols, stain_cols), ccc_sds_cols)
    ha_cols = plasmid_cols
    ha         = HeatmapAnnotation(df = ha_df[colSums(m) != 0,], col=ha_cols, show_legend=FALSE, gp = gpar(fontsize = 100), height = unit(5, "cm"), annotation_name_gp= gpar(fontsize = 7.5), annotation_height = unit(5, "cm"), simple_anno_size = unit(.25, "cm"))
    # row_ha = rowAnnotation(foo = anno_mark(at = (1:dim(m)[1])[rownames(m) %in% adata$var_names[adata$var$sel == 'T']], labels =rownames(m)[rownames(m) %in% adata$var_names[adata$var$sel == 'T']], labels_gp = gpar(fontsize = 15)))
    # row_annot  = Heatmap(
    #     # adata$varm$sig_mask, 
    #     adata[,adata$var$tme_tumor != 'NaN']$varm$sig_mask, 
    #     column_names_gp=gpar(fontsize = 30), 
    #     row_names_gp=gpar(fontsize =30),
    #     # right_annotation = row_ha,
    #     # show_row_names = FALSE,
    #     # row_names_gp=gpar(fontsize = ifelse(rownames(m) %in% adata$var_names[adata$var$sel == 'T'], 50, 0)), 
    #     name = "mat1", width = unit(20, "cm"), cluster_columns = FALSE, col=bl_red
    # )
    # ra = Heatmap(adata$var[adata$var$tme_tumor != 'NaN',]['tme_tumor'], name='celltypes', width = unit(2, "cm"), col= celltype_cols, show_legend= c(df=FALSE), simple_anno_size = unit(1.5, "cm"))

    # pdf(sprintf('output/%s_%s_hm_g2p.pdf', region, adata_tag), width =40, height=40)
    m[is.nan(m)] <- 0
    # column_order = column_order[colnames(m)]
    m = m[,colSums(m) != 0 ]
    # split=factor(ifelse(adata$var[gene_inc,]['tme'] != 'NaN', 'TME', 'Tumor'), levels=c('Tumor', 'TME'))[rowSums(m) != 0]

    m = m[rowSums(m) != 0, ]
    row_ha = rowAnnotation(foo = anno_mark(at = (1:dim(m)[1])[rownames(m) %in% adata$var_names[adata$var$tme_tumor != 'NaN']], labels =rownames(m)[rownames(m) %in% adata$var_names[adata$var$tme_tumor != 'NaN']], labels_gp = gpar(fontsize = 5)))
    ra = Heatmap(adata$var[gene_inc,][rowSums(m) != 0,]['tme_tumor'], name='signature', 
            width = unit(.5, "cm"), col= celltype_cols, 
            right_annotation = row_ha, show_row_names = FALSE,
            row_names_gp=gpar(fontsize =5),column_names_gp=gpar(fontsize = 0),
        )
    # seriate_obj  = seriate(as.matrix(m[rownames(m) %in% adata$var_names[adata$var$tme != 'NaN'],]), method = "PCA")
    seriate_obj  = seriate(as.matrix(m), method = "BEA_TSP")
    row_order    = get_order(seriate_obj, 1)
    column_order = get_order(seriate_obj, 2)
    split = cutree(hclust(as.dist(1- cor(t(m), method='spearman'))), k = 12)
    split = split[names(sort(row_order))]
    text_split = unique(split) %>% map(~paste(names(split[split == .x]), collapse=', '))
    text_split = unique(split) %>% map(~names(split[split == .x]))
    names(text_split) = unique(split)
    # col_dend = order.dendrogram(as.dendrogram(hclust(as.dist(1- cor(m[rownames(m) %in% adata$var_names[adata$var$tme != 'NaN'],], method='spearman')))))
    gg = Heatmap(m^2, 
        # row_split=split, 
        # column_split=20,
        # row_names_gp=gpar(fontsize = 40),
        row_order=row_order,
        # column_order=column_order, 
        # clustering_distance_rows = "spearman",
        # clustering_distance_columns = 'spearman' ,
        # left_annotation = rowAnnotation(
        #     textbox = anno_textbox(split, text_split, gp = gpar(fontsize = 6.5, col = "black"), 
        #     max_width = unit(4, "cm"), background_gp = gpar(fill = "white", col = '#666666'), 
        #     side = "left", word_wrap=TRUE)#, by = "anno_block")
        # ),
        rect_gp = gpar(col = NA, lwd = 0), 
        row_title_gp = gpar(fontsize = 0),
        # right_annotation = ra,
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        # clustering_distance_rows = 'pearson',
        # clustering_method_rows = "single",
        # clustering_method_columns = "single",
        # clustering_distance_columns = 'spearman',
        # clustering_distance_row = function(x) 1 - as.dist( x %*% t(x) / (sqrt(rowSums(x^2) %*% t(rowSums(x^2)))) ) ,
        row_names_gp=gpar(fontsize = 30),
        row_gap = unit(.5, "mm"),
        # cluster_row_slices = FALSE,
        column_names_gp=gpar(fontsize = 0),
        name="Scaled\nGene Expression", column_title = region,  column_title_gp = gpar(fontsize = 20, fontface = "bold"), top_annotation =ha, col=grp_cols) + ra
    draw(gg, padding = unit(c(50, 50, 10, 25), "mm")) #, show_heatmap_legend = FALSE)
    # dev.off()
        # cat('\n\n')
    }
dev.off()

```


```{r}
pdf('output/hm_g2p_total_nodules_local_2024_02_15.pdf', width =20, height=12)
for(region in regions[1]){
    adata = anndata::read_h5ad('data_tidy/new_geno_nodule_2024_02_14.h5ad')
    # adata$var$tme_tumor = ifelse(adata$var$tme != 'NaN', adata$var$tme, ifelse(adata$var$tumor != 'NaN', adata$var$tumor, ifelse(adata$var$add_on != 'NaN', adata$var$add_on, 'NaN')))
    adata$var$tme_tumor = ifelse(adata$var$tme != 'NaN', adata$var$tme, ifelse(adata$var$tumor != 'NaN', adata$var$tumor, 'NaN'))
    adata$layers[['inside']] = adata$X
    core_genes = adata$var_names[adata$var$tme_tumor != 'add_on']
    # adata$layers[[region]] = t(apply(t(adata$layers[[region]]), 2, function(x) (x)/(sum(x))))
    # adata$layers[[region]][is.nan(adata$layers[[region]])] <- 0
    m  = t(adata$layers[[region]])
    # m  = m[gene_inc,]
    # m  = 
    adata = adata[colSums(m) > quantile(colSums(m), 0.2),]
    m  = t(adata$layers[[region]])
    # m  = t(adata$layers[[region]])
    # # m = m[,colSums(m) > 500]
    # m  = m[adata$var$tme_tumor != 'NaN',]
    # mtx[[region]][[adata_tag]] = m
    # m  = apply(m, 2, function(x) (x)/(sum(x)))
    # m[is.nan(m)] <- 0
    # m = t(t(m)/colData(ad)$expected_number)
    # m  = t(apply(m, 1, function(x) ((x)/(max(x)))))
    m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, 0.99), 1, ifelse(x < quantile(x, 0.25), 0, (x - quantile(x, 0.25)) / (quantile(x, 0.99) - quantile(x, 0.25))))))
    m[is.nan(m)] <- 0

    grp_vals     = seq(0, 1, length.out=15)
    grp_cols     = circlize::colorRamp2(grp_vals, pals::ocean.thermal(15))
    # grp_cols     = circlize::colorRamp2(c(quantile(m, 0.35), quantile(m, 0.45), quantile(m, 0.95)), c("#00bfff", "white", "#A10037"))
    stain_df     = adata$obs[,grep(paste0('^',region), colnames(adata$obs))]
    ccc_sds_df   = adata$obs[,c('CCC_score', 'SDS_score')]
    ccc_sds_cr   = colorRamp2(c(0, 1), c("white", "blue"))
    ccc_sds_cols = ccc_sds_df %>% map(function(x) ccc_sds_cr)
    plasmid_mask = rev(data.frame((adata$obsm$plasmid_mask)))
    # ccc_sds_scores[[region]][[adata_tag]] = as.matrix(adata$obs[,c('CCC_score', 'SDS_score')]) * adata$obs$expected_number
    # ha_df      = cbind(ccc_sds_df^5, stain_df, plasmid_mask^5)
    ha_df      = cbind(plasmid_mask^5)
    stain_cr   = colorRamp2(c(0, 1), c("white", "green"))
    stain_cols = stain_df %>% map(function(x) stain_cr)
    # ha_cols    = append(append(plasmid_cols, stain_cols), ccc_sds_cols)
    ha_cols = plasmid_cols
    ha         = HeatmapAnnotation(df = ha_df[colSums(m) != 0,], col=ha_cols, show_legend=FALSE, gp = gpar(fontsize = 100), height = unit(5, "cm"), annotation_name_gp= gpar(fontsize = 7.5), annotation_height = unit(5, "cm"), simple_anno_size = unit(.25, "cm"))
    # row_ha = rowAnnotation(foo = anno_mark(at = (1:dim(m)[1])[rownames(m) %in% adata$var_names[adata$var$sel == 'T']], labels =rownames(m)[rownames(m) %in% adata$var_names[adata$var$sel == 'T']], labels_gp = gpar(fontsize = 15)))
    # row_annot  = Heatmap(
    #     # adata$varm$sig_mask, 
    #     adata[,adata$var$tme_tumor != 'NaN']$varm$sig_mask, 
    #     column_names_gp=gpar(fontsize = 30), 
    #     row_names_gp=gpar(fontsize =30),
    #     # right_annotation = row_ha,
    #     # show_row_names = FALSE,
    #     # row_names_gp=gpar(fontsize = ifelse(rownames(m) %in% adata$var_names[adata$var$sel == 'T'], 50, 0)), 
    #     name = "mat1", width = unit(20, "cm"), cluster_columns = FALSE, col=bl_red
    # )
    

    # pdf(sprintf('output/%s_%s_hm_g2p.pdf', region, adata_tag), width =40, height=40)
    m = m[rownames(m) %in% adata$var_names[adata$var$tme_tumor != 'NaN'],]
    m[is.nan(m)] <- 0
    # column_order = column_order[colnames(m)]
    m = m[,colSums(m) != 0 ]
    split=factor(ifelse(adata$var[rownames(m),]['tme'] != 'NaN', 'TME', ifelse(adata$var[rownames(m),]['tumor'] != 'NaN', 'Tumor', 'add_on')), levels=c('Tumor', 'TME', 'add_on'))[rowSums(m) != 0]
    m = m[rowSums(m) != 0, ]
    # names(text_split) = unique(split)
    col_dend = dendsort(hclust(dist(plasmid_mask[colnames(m),]^5)))
    # row_ha = rowAnnotation(foo = anno_mark(at = (1:dim(m)[1])[rownames(m) %in% core_genes], labels =rownames(m)[rownames(m) %in% core_genes], labels_gp = gpar(fontsize = 15)))
    df = adata$var[adata$var$tme_tumor != 'NaN',]['tme_tumor'][rownames(m),]
    names(df) = rownames(m)
    ra = Heatmap(df, name='signature', width = unit(0.5, "cm"), row_names_gp=gpar(fontsize = 7.5), col= celltype_cols, show_row_names =TRUE)
    gg = Heatmap(m^2, 
        row_split=split, 
        row_km = 10,
        # column_split = 10,
        # row_split=adata$var[rownames(m),]$tme_tumor, 
        # column_split=20,
        # row_names_gp=gpar(fontsize = 40),
        # row_order=row_order,
        # column_order=column_order, 
        # clustering_distance_rows = "pearson",
        # clustering_distance_columns = 'pearson' ,
        # right_annotation = row_ha,
        # right_annotation = rowAnnotation(
        #     textbox = anno_textbox(split, text_split, gp = gpar(fontsize = 10, col = "black"), 
        #     max_width = unit(20, "cm"), background_gp = gpar(fill = "white", col = '#666666'), 
        #     side = "right", word_wrap=TRUE)#, by = "anno_block")
        # ),
        # row_names_gp=gpar(fontsize = ifelse(rownames(m) %in% core_genes, 7.5, 1)),
        # rect_gp = gpar(col = NA, lwd = 0), 
        row_title_gp = gpar(fontsize = 15),
        row_title = "%s|%s",
        # row_title_gp = gpar(fontsize = 15),
        # row_dend_reorder = TRUE,
        column_dend_reorder = TRUE,
        # cluster_columns = col_dend,
        # right_annotation = ra,
        # show_column_dend = FALSE,
        # show_row_dend = FALSE,
        # clustering_distance_rows = 'spearman',
        # clustering_method_rows = "spearman",
        # clustering_method_columns = "spearman",
        # clustering_distance_columns = 'spearman',
        # clustering_distance_columns = function(x, y) 1 - cor(x[intersect(rownames(m), core_genes)], y[intersect(rownames(m), core_genes)], method='spearman') ,
        # clustering_distance_rows = function(x, y) 1- (sum(x[intersect(rownames(m), core_genes)] * y[intersect(rownames(m), core_genes)]))/(norm(x[intersect(rownames(m), core_genes)]) * norm(y[intersect(rownames(m), core_genes)])),
        row_names_gp=gpar(fontsize = 7.5),
        row_gap = unit(.5, "mm"),
        column_gap = unit(.5, "mm"),
        cluster_row_slices = FALSE,
        show_row_names =FALSE,
        column_names_gp=gpar(fontsize = 0),
        name="Scaled\nGene Expression", column_title = region,  column_title_gp = gpar(fontsize = 20, fontface = "bold"), top_annotation =ha, col=grp_cols)  + ra
    draw(gg, padding = unit(c(20, 20, 10, 25), "mm"))#, show_heatmap_legend = FALSE)
    # dev.off()
        # cat('\n\n')
    }
dev.off()
```



```{r}
q_high = 0.95
q_low  = 0.25
adata = anndata::read_h5ad('data_tidy/new_geno_nodule_2024_02_.h5ad')
keys_6ROI = c('ML_III_A', 'ML_III_B', 'ML_II_A_1','ML_II_B', 'ML_II_C', 'ML_I_2')
adata = adata[adata$obs$sample %in% keys_6ROI,]
adata$var$tme_tumor = ifelse(adata$var$tme != 'NaN', adata$var$tme, ifelse(adata$var$tumor != 'NaN', adata$var$tumor, 'NaN'))
tumor_core = adata$var_names[adata$var$tumor != 'add_on' & adata$var$tumor != 'NaN']
tme_core = adata$var_names[adata$var$tme != 'add_on' & adata$var$tme != 'NaN']
m  = t(adata[['X']])
adata = adata[colSums(m) > quantile(colSums(m), 0.2),]
m  = t(adata[['X']])
m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, q_high), 1, ifelse(x < quantile(x, q_low), 0, (x - quantile(x, q_low)) / (quantile(x, q_high) - quantile(x, 0.25))))))
m[is.nan(m)] <- 0

grp_vals     = seq(0, 1, length.out=20)
grp_cols     = circlize::colorRamp2(grp_vals, pals::ocean.thermal(20))
plasmid_mask = rev(data.frame((adata$obsm$plasmid_mask)))
tumor_mask   = adata$obs[, setdiff(paste0(tumor_order, '_bin'), 'Unclassified_bin')]
tme_mask   = adata$obs[, paste0(tme_order, '_bin')]
# ha_df      = cbind(plasmid_mask^10, tumor_mask, tme_mask)
ha_df      = cbind(plasmid_mask^10)
ha_cols = c(plasmid_cols, tumor_colors, tme_colors)
ha_tumor         = HeatmapAnnotation(df = ha_df[colSums(m) != 0,], col=ha_cols, show_legend=FALSE, gp = gpar(fontsize = 100), height = unit(5, "cm"), annotation_name_gp= gpar(fontsize = 7.5), annotation_height = unit(5, "cm"), simple_anno_size = unit(.25, "cm"))
ha_tme         = HeatmapAnnotation(df = rev(ha_df[colSums(m) != 0,]), col=ha_cols, show_legend=FALSE, gp = gpar(fontsize = 100), height = unit(5, "cm"), annotation_name_gp= gpar(fontsize = 7.5), annotation_height = unit(5, "cm"), simple_anno_size = unit(.25, "cm"))

m = m[rownames(m) %in% adata$var_names[adata$var$tme_tumor != 'NaN'],]
m[is.nan(m)] <- 0
m = m[,colSums(m) != 0 ]
split=factor(ifelse(adata$var[rownames(m),]['tme'] != 'NaN', 'TME', ifelse(adata$var[rownames(m),]['tumor'] != 'NaN', 'Tumor', 'add_on')), levels=c('Tumor', 'TME', 'add_on'))[rowSums(m) != 0]
m = m[rowSums(m) != 0, ]
# col_dend = dendsort(hclust(dist(plasmid_mask[colnames(m),]^5)))
# row_dend = as.dendrogram(hclust(as.dist(1- cor(t(m[rownames(m) %in% tumor_core | rownames(m) %in% tme_core,]), method='spearman'))))


df_tumor = adata$var[adata$var$tumor != 'NaN',]['tumor']
tumor_genes = rownames(df_tumor)[rownames(df_tumor) %in% rownames(m)]
df_tumor = df_tumor[tumor_genes,]
names(df_tumor) = tumor_genes
row_dend_tumor = as.dendrogram(hclust(as.dist(1- cor(t(m[tumor_genes,]), method='pearson'))))
# tumor_core = names(df_tumor) = rownames(m)[rownames(m) %in% tumor_core]
# ra_tumor = Heatmap(df_tumor, name='signature', width = unit(0.5, "cm"), column_names_gp=gpar(fontsize = 0), row_names_gp=gpar(fontsize = 7.5), col= celltype_cols, show_row_names =TRUE)
ra_tumor = rowAnnotation(Tumor=df_tumor,col= list(Tumor=celltype_cols_static[as.character(unique(df_tumor))]), annotation_name_gp= gpar(fontsize = 0))
set.seed(1375)
column_order = order(factor(adata[colnames(m),]$obs[,'dom_type'], ordered=TRUE, levels = c(tumor_order, 'add_on')))
col_split =  factor(adata[colnames(m),]$obs[,'dom_tumor'], ordered=TRUE, levels = tumor_order)
hm_tumor = Heatmap(
        m[tumor_genes,]^2, 
        cluster_rows = row_dend_tumor,
        row_split=6, 
        column_split = col_split, 
        # row_order = names(sort(df_tumor, decreasing=FALSE)),
        # column_order = column_order,
        row_title_gp = gpar(fontsize = 0),
        # row_dend_reorder = FALSE,
        row_names_gp=gpar(fontsize = 7.5),
        row_gap = unit(.2, "mm"),
        column_gap = unit(.5, "mm"),
        left_annotation = ra_tumor,
        # cluster_row_slices = FALSE,
        # cluster_columns = col_dend,
        # cluster_row_slices = FALSE,
        cluster_column_slices = FALSE,
        clustering_distance_rows = 'spearman',
        # show_row_names =FALSE,
        # show_column_dend = FALSE,
        column_names_gp=gpar(fontsize = 0),
        name="Scaled\nGene Expression", #column_title = region,  
        column_title_gp = gpar(fontsize = 10, fontface = "bold", rot=35), 
        column_title_rot = 45,
        bottom_annotation =ha_tumor, col=grp_cols,
        cluster_row_slices = FALSE,
        show_column_dend = FALSE,
        row_names_side = 'left',
        row_names_centered = TRUE,
        show_row_dend = FALSE,
        width = unit(15, "cm"),
        height= unit(10, "cm"),
        
    )  # + ra_tumor

# lgd_tumor = Legend(labels = setdiff(unique(adata$var$tumor), c('NaN', 'add_on')), title = "TME", legend_gp = gpar(col = celltype_cols_static),
#     title_position = "leftcenter-rot")

df_tme = adata$var[adata$var$tme != 'NaN',]['tme']
tme_genes = rownames(df_tme)[rownames(df_tme) %in% rownames(m)]
tme_genes = setdiff(tme_genes, 'Postn')
df_tme = df_tme[tme_genes,]
names(df_tme) = tme_genes
# tme_core = names(df_tme) = rownames(m)[rownames(m) %in% tme_core]
# ra_tme = Heatmap(df_tme, name='signature', width = unit(0.5, "cm"), row_names_gp=gpar(fontsize = 7.5), col= celltype_cols_static, show_row_names =TRUE)
ra_tme = rowAnnotation(TME=df_tme,col= list(TME=celltype_cols_static[as.character(unique(df_tme))]), annotation_name_gp= gpar(fontsize = 0))
set.seed(1375)
# m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, q_high), 1, ifelse(x < quantile(x, q_low), 0, (x - quantile(x, q_low)) / (quantile(x, q_high) - quantile(x, 0.25))))))
row_dend_tme = hclust(as.dist(1- cor(t(m[tme_genes,]^2), method='pearson')))
row_split = cutree(row_dend_tme , k = 9)
# row_order = 
hm_tme = Heatmap(
        m[tme_genes,]^2, 
        row_split=7, 
        column_split = col_split,
        # row_km_repeats = 10000,
        row_title_gp = gpar(fontsize = 0),
        # row_order = names(sort(df_tme, decreasing=TRUE)),
        column_dend_reorder = TRUE,
        row_names_gp=gpar(fontsize = 7.5),
        row_gap = unit(.2, "mm"),
        column_gap = unit(.5, "mm"),
        # cluster_columns = col_dend,
        # cluster_row_slices = FALSE,
        cluster_column_slices = FALSE,
        clustering_distance_rows = 'spearman',
        left_annotation = ra_tme,
        row_names_side = 'left',
        # show_row_names =FALSE,
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        column_names_gp=gpar(fontsize = 0),
        name="Scaled\nGene Expression",# column_title = region,  
        column_title_gp = gpar(fontsize = 10, fontface = "bold"), 
        # cluster_row_slices = FALSE,
        column_title_rot = 45,
        col=grp_cols,
        top_annotation =ha_tme,
        cluster_rows = as.dendrogram(row_dend_tme),
        height = unit(10, "cm"),
        width = unit(15, "cm"),
        row_names_centered = TRUE,

    )  #+ ra_tme 


hm_all = (hm_tumor %v% hm_tme)


pdf('output/hm_g2p_total_nodules_local_2024_02_22.pdf', width =20, height=15)
draw(hm_all, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_total_nodules_local_tumor_only_2024_02_22.pdf', width =20, height=9)
draw(hm_tumor, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE)#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_total_nodules_local_tme_only_2024_02_22.pdf', width =20, height=9)
draw(hm_tme, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE)#, show_heatmap_legend = FALSE) 

dev.off()
    # cat('\n\n')

ra_celltype = rowAnnotation(celltype=c(df_tumor, df_tme),col= list(celltype=celltype_cols_static[as.character(c(unique(df_tumor), unique(df_tme)))]), annotation_name_gp= gpar(fontsize = 0))
grp_vals_cor     = seq(-1, 1, length.out=15)
grp_cols_cor     = circlize::colorRamp2(grp_vals_cor, pals::ocean.curl(15))

ha_tme = HeatmapAnnotation(TME=df_tme,col= list(TME=celltype_cols_static[as.character(unique(df_tme))]), annotation_name_gp= gpar(fontsize = 0))
hm_cor = Heatmap(
        cor(t(m[names(c(df_tumor)),]), t(m[names(c(df_tme)),])), #), method='spearman'), 
        # right_annotation = ra_tumor,
        name="Pearson's \ncor. coefficient", #column_title = region,  
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        col=grp_cols_cor,
        # clustering_method_rows = "single",
        cluster_rows = as.dendrogram(row_dend_tumor),
        # clustering_method_columns = "single",
        column_dend_reorder = FALSE,
        show_row_names = FALSE,
        show_column_names = FALSE,
        # bottom_annotation   = ha_tme,
        cluster_columns = rev(as.dendrogram(row_dend_tme)),
        row_split= 6,
        column_split=7,
         column_title_gp = gpar(fontsize = 0, fontface = "bold"),
         row_title_gp = gpar(fontsize = 0, fontface = "bold"),
        width = unit(10, "cm"),
        height= unit(10, "cm"),
    )  #+ ra_tme

hm_both = (hm_cor + hm_tumor ) 
# draw(hm_both, auto_adjust = FALSE)
pdf('output/hm_g2p_corr_genes_2024_02_28.pdf', width =18, height=10)
draw(hm_both, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE, auto_adjust = FALSE)#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_tme_2024_02_28.pdf', width = 10, height = 12)
draw(hm_tme, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE, auto_adjust=FALSE)#, show_heatmap_legend = FALSE) 

dev.off()



```


```{r}
q_high = 0.95
q_low  = 0.25
adata = anndata::read_h5ad('data_tidy/new_geno_nodule_2024_04_03.h5ad')
keys_6ROI = c('ML_III_A', 'ML_III_B', 'ML_II_A_1','ML_II_B', 'ML_II_C', 'ML_I_2')
adata = adata[adata$obs$sample %in% keys_6ROI,]
adata$var$tme_tumor = ifelse(adata$var$tme != 'NaN', adata$var$tme, ifelse(adata$var$tumor != 'NaN', adata$var$tumor, 'NaN'))
tumor_core = adata$var_names[adata$var$tumor != 'add_on' & adata$var$tumor != 'NaN']
tme_core = adata$var_names[adata$var$tme != 'add_on' & adata$var$tme != 'NaN']
m  = t(adata[['X']])
adata = adata[colSums(m) > quantile(colSums(m), 0.2),]
m  = t(adata[['X']])
m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, q_high), 1, ifelse(x < quantile(x, q_low), 0, (x - quantile(x, q_low)) / (quantile(x, q_high) - quantile(x, 0.25))))))
m[is.nan(m)] <- 0

grp_vals     = seq(0, 1, length.out=20)
grp_cols     = circlize::colorRamp2(grp_vals, pals::ocean.thermal(20))
adata$obsm$plasmid_mask = adata$obsm$plasmid_mask[,plasmid_order]
plasmid_mask = rev(data.frame((adata$obsm$plasmid_mask)))
tumor_mask   = adata$obs[, intersect(colnames(adata$obs), setdiff(paste0(tumor_order, '_bin'), 'Unclassified_bin'))]
tme_mask   = adata$obs[, paste0(tme_order, '_bin')]
# ha_df      = cbind(plasmid_mask^10, tumor_mask, tme_mask)
ha_df      = cbind(plasmid_mask^10)
ha_cols = c(plasmid_cols, tumor_colors, tme_colors)
ha_tumor  = HeatmapAnnotation(
        df = ha_df[colSums(m) != 0,], 
        col=ha_cols, show_legend=TRUE, 
        gp = gpar(fontsize = 100), 
        height = unit(1, "cm"), 
        annotation_name_gp= gpar(fontsize = 0), 
        annotation_height = unit(1, "cm"), 
        simple_anno_size = unit(.1, "cm"),         
        annotation_legend_param = list(direction = "horizontal", at = c(0, 1), labels_gp = gpar(font=1), legend_width = unit(3, "cm"), title_position = "topcenter")
    )



m = m[rownames(m) %in% adata$var_names[adata$var$tme_tumor != 'NaN'],]
m[is.nan(m)] <- 0
m = m[,colSums(m) != 0 ]
split=factor(ifelse(adata$var[rownames(m),]['tme'] != 'NaN', 'TME', ifelse(adata$var[rownames(m),]['tumor'] != 'NaN', 'Tumor', 'add_on')), levels=c('Tumor', 'TME', 'add_on'))[rowSums(m) != 0]
m = m[rowSums(m) != 0, ]
# col_dend = dendsort(hclust(dist(plasmid_mask[colnames(m),]^5)))
# row_dend = as.dendrogram(hclust(as.dist(1- cor(t(m[rownames(m) %in% tumor_core | rownames(m) %in% tme_core,]), method='spearman'))))


df_tumor = adata$var[adata$var$tumor != 'NaN',]['tumor']
tumor_genes = rownames(df_tumor)[rownames(df_tumor) %in% rownames(m)]
tumor_genes = setdiff(tumor_genes, 'Vil1')
df_tumor = df_tumor[tumor_genes,]
names(df_tumor) = tumor_genes
df_tumor =  as.character(df_tumor)
names(df_tumor) = tumor_genes
row_dend_tumor = hclust(as.dist(1- cor(t(m[tumor_genes,]), method='pearson')))
row_split_tumor = cutree(row_dend_tumor, k= 7)
row_split_tumor = (max(row_split_tumor)+1) - row_split_tumor %>% map(~max(match(df_tumor[names(which(row_split_tumor == .x))], tumor_genes_order))) %>% unlist()
# max(match(df_tumor[names(which(row_split_tumor == 2))], tumor_order))
# tumor_core = names(df_tumor) = rownames(m)[rownames(m) %in% tumor_core]
# ra_tumor = Heatmap(df_tumor, name='signature', width = unit(0.5, "cm"), column_names_gp=gpar(fontsize = 0), row_names_gp=gpar(fontsize = 7.5), col= celltype_cols, show_row_names =TRUE)
ra_tumor = rowAnnotation(Tumor=df_tumor,col= list(Tumor=celltype_cols_static[as.character(unique(df_tumor))]), annotation_name_gp= gpar(fontsize = 0))
set.seed(1375)
# column_order = order(factor(adata[colnames(m),]$obs[,'dom_type'], ordered=TRUE, levels = c(tumor_order, 'add_on')))
col_split =  factor(adata[colnames(m),]$obs[,'dom_tumor'], ordered=TRUE, levels = rev(tumor_order))
# m = m[tumor_genes,]
hm_tumor = Heatmap(
        m[tumor_genes,]^2, 
        # cluster_rows = row_dend_tumor,
        row_split=row_split_tumor, 
        column_split = factor(abv_types[as.character(col_split)], ordered=TRUE, levels=rev(abv_types)), 
        # row_order = names(sort(df_tumor, decreasing=FALSE)),
        # column_order = column_order,
        row_title_gp = gpar(fontsize = 0),
        # row_dend_reorder = FALSE,
        row_names_gp=gpar(fontsize = 7.5),
        row_gap = unit(.2, "mm"),
        column_gap = unit(.2, "mm"),
        left_annotation = ra_tumor,
        # cluster_row_slices = FALSE,
        # cluster_columns = col_dend,
        # cluster_row_slices = FALSE,
        cluster_column_slices = FALSE,
        # clustering_distance_rows = 'spearman',
        # show_row_names =FALSE,
        # show_column_dend = FALSE,
        row_names_side = 'left',
        column_names_gp=gpar(fontsize = 0),
        name="Scaled\nGene Expression", #column_title = region,  
        column_title_gp = gpar(fontsize = 7.5, rot=0), 
        column_title_rot = 0,
        bottom_annotation =ha_tumor, col=grp_cols,
        cluster_row_slices = FALSE,
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        width = unit(15, "cm"),
        height= unit(10, "cm"),
        row_names_centered = TRUE,

        
    )  # + ra_tumor

# lgd_tumor = Legend(labels = setdiff(unique(adata$var$tumor), c('NaN', 'add_on')), title = "TME", legend_gp = gpar(col = celltype_cols_static),
#     title_position = "leftcenter-rot")

df_tme = adata$var[adata$var$tme != 'NaN',]['tme']
tme_genes = rownames(df_tme)[rownames(df_tme) %in% rownames(m)]
tme_genes = setdiff(tme_genes, 'Postn')
df_tme = df_tme[tme_genes,]
names(df_tme) = tme_genes
# tme_core = names(df_tme) = rownames(m)[rownames(m) %in% tme_core]
# ra_tme = Heatmap(df_tme, name='signature', width = unit(0.5, "cm"), row_names_gp=gpar(fontsize = 7.5), col= celltype_cols_static, show_row_names =TRUE)
set.seed(1375)
row_dend_tme = hclust(as.dist(1- cor(t(m[tme_genes,]), method='pearson')))
row_split_tme = cutree(row_dend_tme, k= 10)
row_split_tme = (max(row_split_tme)+1) - (row_split_tme %>% map(~max(match(df_tme[names(which(row_split_tme == .x))], rev(tme_genes_order)))) %>% unlist())
ra_tme = rowAnnotation(TME=df_tme,col= list(TME=celltype_cols_static[as.character(unique(df_tme))]), annotation_name_gp= gpar(fontsize = 0))
# m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, q_high), 1, ifelse(x < quantile(x, q_low), 0, (x - quantile(x, q_low)) / (quantile(x, q_high) - quantile(x, 0.25))))))
# row_dend_tme = hclust(as.dist(1- cor(t(m[tme_genes,]^2), method='pearson')))
# row_split = cutree(row_dend_tme , k = 10)
# row_order = 

m2  = t(adata$layers[['quantiles']])
m2  = m2[, colnames(m)]
m2  = t(apply(m2, 1, function(x) ifelse(x > quantile(x, q_high), 1, ifelse(x < quantile(x, q_low), 0, (x - quantile(x, q_low)) / (quantile(x, q_high) - quantile(x, 0.25))))))
m2[is.nan(m2)] <- 0
ha_tme        = HeatmapAnnotation(df = rev(ha_df), col=ha_cols, show_legend=FALSE, gp = gpar(fontsize = 100), height = unit(1, "cm"), annotation_name_gp= gpar(fontsize = 2), annotation_height = unit(1, "cm"), simple_anno_size = unit(.1, "cm"))
col_split = ifelse(col_split == 'Normal', 'Normal', 'Tumor')
hm_tme = Heatmap(
        m2[tme_genes,]^2, 
        row_split=row_split_tme, 
        column_split = factor(col_split, ordered=TRUE, levels=c('Tumor', 'Normal')),
        # column_split = factor(abv_types[as.character(col_split)], ordered=TRUE, levels=abv_types), 
        # row_km_repeats = 10000,
        row_title_gp = gpar(fontsize = 0),
        # row_order = names(sort(df_tme, decreasing=TRUE)),
        column_dend_reorder = FALSE,
        row_names_gp=gpar(fontsize = 7.5),
        row_gap = unit(.2, "mm"),
        column_gap = unit(.2, "mm"),
        # cluster_columns = col_dend,
        # cluster_row_slices = FALSE,
        # clustering_distance_rows = 'spearman',
        left_annotation = ra_tme,
        cluster_column_slices=FALSE,
        cluster_row_slices = FALSE,
        # show_row_names =FALSE,
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        column_names_gp=gpar(fontsize = 0),
        name="Scaled\nGene Expression",# column_title = region,  
        column_title_gp = gpar(fontsize = 10), 
        # cluster_row_slices = FALSE,
        column_title_rot = 0,
        col=grp_cols,
        top_annotation =ha_tme,
        # cluster_rows = as.dendrogram(row_dend_tme), 
        height = unit(10, "cm"),
        width = unit(15, "cm"),
        row_names_centered = TRUE,
        row_names_side = 'left',
        # annotation_legend_param = list(title_position ='leftcenter-rot'),

    )  #+ ra_tme 


hm_all = (hm_tumor %v% hm_tme)


pdf('output/hm_g2p_all_2024_04_03.pdf', width =20, height=20)
draw(hm_all, padding = unit(c(20, 25, 10, 25), "mm"))#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_total_nodules_local_tumor_only_2024_04_03.pdf', width =20, height=9)
draw(hm_tumor, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE)#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_total_nodules_local_tme_only_2024_04_03.pdf', width =15, height=9)
draw(hm_tme, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE)#, show_heatmap_legend = FALSE) 

dev.off()
    # cat('\n\n')

ra_celltype = rowAnnotation(celltype=c(df_tumor, df_tme),col= list(celltype=celltype_cols_static[as.character(c(unique(df_tumor), unique(df_tme)))]), annotation_name_gp= gpar(fontsize = 0))
grp_vals_cor     = seq(-1, 1, length.out=15)
grp_cols_cor     = circlize::colorRamp2(grp_vals_cor, rev(colorspace::divergingx_hcl(15, palette='PiYG')))

ha_tme = HeatmapAnnotation(TME=df_tme,col= list(TME=celltype_cols_static[as.character(unique(df_tme))]), annotation_name_gp= gpar(fontsize = 0))
hm_cor = Heatmap(
        cor(t(m[names(c(df_tumor)),]), t(m2[names(c(df_tme)),])), #), method='spearman'), 
        # right_annotation = ra_tumor,
        name="Pearson's \ncor. coefficient", #column_title = region,  
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        col=grp_cols_cor,
        # clustering_method_rows = "single",
        # clustering_method_columns = "single",
        column_dend_reorder = FALSE,
        show_row_names = FALSE,
        show_column_names = FALSE,
        cluster_row_slices = FALSE,
        cluster_column_slices = FALSE,
        # bottom_annotation   = ha_tme,
        # cluster_rows = row_dend_tumor,
        # cluster_columns = rev(row_dend_tme),
        row_gap = unit(.2, "mm"),
        column_gap = unit(.2, "mm"),
        row_split= row_split_tumor,
        column_split=max(row_split_tme) - row_split_tme + 1,
         column_title_gp = gpar(fontsize = 0, fontface = "bold"),
         row_title_gp = gpar(fontsize = 0, fontface = "bold"),
        width = unit(10, "cm"),
        height= unit(10, "cm"),
    )  #+ ra_tme

hm_both = (hm_cor + hm_tumor ) 
# draw(hm_both, auto_adjust = FALSE)
pdf('output/hm_g2p_corr_genes_2024_04_03.pdf', width =18, height=10)
draw(hm_both, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE, auto_adjust = FALSE)#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_tme_2024_03_06.pdf', width = 10, height = 12)
draw(hm_tme, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE, auto_adjust=FALSE)#, show_heatmap_legend = FALSE) 

dev.off()


library(rstatix)
plasmid_mask$ID = rownames(plasmid_mask)
p_mask = melt(plasmid_mask)
tumor_mask$ID = rownames(tumor_mask)
tme_mask$ID = rownames(tme_mask)
p_mask = merge(p_mask, tumor_mask, by='ID')
p_mask = merge(p_mask, tme_mask, by='ID')
p_mask %<>% rename('variable'= 'var', 'value' = 'val')
p_mask$var = str_replace(p_mask$var, '.plasmid', '')


p_mask$cholangiocytic_bin = factor(p_mask$cholangiocytic_bin )
bxp <- ggboxplot(
  p_mask, x = "var", y = "val", 
  color = "cholangiocytic_bin", palette = c("#00AFBB", "#E7B800")
  )


stat.test <- p_mask %>%
  group_by(var) %>%
  t_test(val ~ cholangiocytic_bin) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj")

library(rstatix)
# Add p-values onto the box plots
stat.test <- stat.test %>%
  add_xy_position(x = "var", dodge = 0.8)
bxp + stat_pvalue_manual(
  stat.test,  label = "p", tip.length = 0
  )

# Add 10% spaces between the p-value labels and the plot border
bxp + stat_pvalue_manual(
  stat.test,  label = "p", tip.length = 0
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) + theme_minimal()



```



```{r}
q_high = 0.95
q_low  = 0.25
adata = anndata::read_h5ad('data_tidy/new_geno_nodule_2024_03_27.h5ad')

for(s in unique(adata$obs$sample)[1]){
    adata_s = adata[adata$obs$sample == s, ]
    adata_s$obsm$plasmid_mask = adata_s$obsm$plasmid_mask[,plasmid_order]
    plasmid_mask = rev(data.frame((adata_s$obsm$plasmid_mask)))
    # tumor_mask   = adata_s$obs[, intersect(colnames(adata_s$obs), setdiff(paste0(tumor_order, '_bin'), 'Unclassified_bin'))]
    # tme_mask   = adata_s$obs[, paste0(tme_order, '_bin')]
    # ha_df      = cbind(plasmid_mask^10, tumor_mask, tme_mask)
    ha_df      = cbind(plasmid_mask^10)
    ha_cols = c(plasmid_cols, tumor_colors, tme_colors)
    col_dend = dendsort(hclust(dist(plasmid_mask^10)))
    ha_tumor  = HeatmapAnnotation(
            df = rev(ha_df[col_dend$order,]), 
            col=ha_cols,#, show_legend=TRUE, 
            gp = gpar(fontsize = 100), 
            height = unit(5, "cm"), 
            annotation_name_gp= gpar(fontsize = 5), 
            annotation_height = unit(1, "cm"), 
            simple_anno_size = unit(1, "cm"),         
            annotation_legend_param = list(direction = "horizontal", at = c(0, 1), labels_gp = gpar(font=1), legend_width = unit(3, "cm"), title_position = "topcenter")
        )

}


hm_tumor = Heatmap(
        m[tumor_genes,]^2, 
        # cluster_rows = row_dend_tumor,
        row_split=row_split_tumor, 
        column_split = factor(abv_types[as.character(col_split)], ordered=TRUE, levels=rev(abv_types)), 
        # row_order = names(sort(df_tumor, decreasing=FALSE)),
        # column_order = column_order,
        row_title_gp = gpar(fontsize = 0),
        # row_dend_reorder = FALSE,
        row_names_gp=gpar(fontsize = 7.5),
        row_gap = unit(.2, "mm"),
        column_gap = unit(.2, "mm"),
        left_annotation = ra_tumor,
        # cluster_row_slices = FALSE,
        # cluster_columns = col_dend,
        # cluster_row_slices = FALSE,
        cluster_column_slices = FALSE,
        # clustering_distance_rows = 'spearman',
        # show_row_names =FALSE,
        # show_column_dend = FALSE,
        row_names_side = 'left',
        column_names_gp=gpar(fontsize = 0),
        name="Scaled\nGene Expression", #column_title = region,  
        column_title_gp = gpar(fontsize = 7.5, rot=0), 
        column_title_rot = 0,
        bottom_annotation =ha_tumor, col=grp_cols,
        cluster_row_slices = FALSE,
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        width = unit(15, "cm"),
        height= unit(10, "cm"),
        row_names_centered = TRUE,

        
    )  # + ra_tumor

# lgd_tumor = Legend(labels = setdiff(unique(adata$var$tumor), c('NaN', 'add_on')), title = "TME", legend_gp = gpar(col = celltype_cols_static),
#     title_position = "leftcenter-rot")

df_tme = adata$var[adata$var$tme != 'NaN',]['tme']
tme_genes = rownames(df_tme)[rownames(df_tme) %in% rownames(m)]
tme_genes = setdiff(tme_genes, 'Postn')
df_tme = df_tme[tme_genes,]
names(df_tme) = tme_genes
# tme_core = names(df_tme) = rownames(m)[rownames(m) %in% tme_core]
# ra_tme = Heatmap(df_tme, name='signature', width = unit(0.5, "cm"), row_names_gp=gpar(fontsize = 7.5), col= celltype_cols_static, show_row_names =TRUE)
set.seed(1375)
row_dend_tme = hclust(as.dist(1- cor(t(m[tme_genes,]), method='pearson')))
row_split_tme = cutree(row_dend_tme, k= 10)
row_split_tme = (max(row_split_tme)+1) - (row_split_tme %>% map(~max(match(df_tme[names(which(row_split_tme == .x))], rev(tme_genes_order)))) %>% unlist())
ra_tme = rowAnnotation(TME=df_tme,col= list(TME=celltype_cols_static[as.character(unique(df_tme))]), annotation_name_gp= gpar(fontsize = 0))
# m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, q_high), 1, ifelse(x < quantile(x, q_low), 0, (x - quantile(x, q_low)) / (quantile(x, q_high) - quantile(x, 0.25))))))
# row_dend_tme = hclust(as.dist(1- cor(t(m[tme_genes,]^2), method='pearson')))
# row_split = cutree(row_dend_tme , k = 10)
# row_order = 

m2  = t(adata$layers[['quantiles']])
m2  = m2[, colnames(m)]
m2  = t(apply(m2, 1, function(x) ifelse(x > quantile(x, q_high), 1, ifelse(x < quantile(x, q_low), 0, (x - quantile(x, q_low)) / (quantile(x, q_high) - quantile(x, 0.25))))))
m2[is.nan(m2)] <- 0
ha_tme        = HeatmapAnnotation(df = rev(ha_df), col=ha_cols, show_legend=FALSE, gp = gpar(fontsize = 100), height = unit(1, "cm"), annotation_name_gp= gpar(fontsize = 2), annotation_height = unit(1, "cm"), simple_anno_size = unit(.1, "cm"))
col_split = ifelse(col_split == 'Normal', 'Normal', 'Tumor')
hm_tme = Heatmap(
        m2[tme_genes,]^2, 
        row_split=row_split_tme, 
        column_split = factor(col_split, ordered=TRUE, levels=c('Tumor', 'Normal')),
        # column_split = factor(abv_types[as.character(col_split)], ordered=TRUE, levels=abv_types), 
        # row_km_repeats = 10000,
        row_title_gp = gpar(fontsize = 0),
        # row_order = names(sort(df_tme, decreasing=TRUE)),
        column_dend_reorder = FALSE,
        row_names_gp=gpar(fontsize = 7.5),
        row_gap = unit(.2, "mm"),
        column_gap = unit(.2, "mm"),
        # cluster_columns = col_dend,
        # cluster_row_slices = FALSE,
        # clustering_distance_rows = 'spearman',
        left_annotation = ra_tme,
        cluster_column_slices=FALSE,
        cluster_row_slices = FALSE,
        # show_row_names =FALSE,
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        column_names_gp=gpar(fontsize = 0),
        name="Scaled\nGene Expression",# column_title = region,  
        column_title_gp = gpar(fontsize = 10), 
        # cluster_row_slices = FALSE,
        column_title_rot = 0,
        col=grp_cols,
        top_annotation =ha_tme,
        # cluster_rows = as.dendrogram(row_dend_tme), 
        height = unit(10, "cm"),
        width = unit(15, "cm"),
        row_names_centered = TRUE,
        row_names_side = 'left'
        annotation_legend_param = list(title_position ='leftcenter-rot'),

    )  #+ ra_tme 


hm_all = (hm_tumor %v% hm_tme)


pdf('output/hm_g2p_total_nodules_tumor_legend_plasmids.pdf', width =20, height=20)
draw(hm_tumor, padding = unit(c(20, 25, 10, 25), "mm"))#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_total_nodules_local_tumor_only_2024_02_22.pdf', width =20, height=9)
draw(hm_tumor, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE)#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_total_nodules_local_tme_only_2024_02_22.pdf', width =20, height=9)
draw(hm_tme, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE)#, show_heatmap_legend = FALSE) 

dev.off()
    # cat('\n\n')

ra_celltype = rowAnnotation(celltype=c(df_tumor, df_tme),col= list(celltype=celltype_cols_static[as.character(c(unique(df_tumor), unique(df_tme)))]), annotation_name_gp= gpar(fontsize = 0))
grp_vals_cor     = seq(-1, 1, length.out=15)
grp_cols_cor     = circlize::colorRamp2(grp_vals_cor, pals::ocean.curl(15))

ha_tme = HeatmapAnnotation(TME=df_tme,col= list(TME=celltype_cols_static[as.character(unique(df_tme))]), annotation_name_gp= gpar(fontsize = 0))
hm_cor = Heatmap(
        cor(t(m[names(c(df_tumor)),]), t(m2[names(c(df_tme)),])), #), method='spearman'), 
        # right_annotation = ra_tumor,
        name="Pearson's \ncor. coefficient", #column_title = region,  
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        col=grp_cols_cor,
        # clustering_method_rows = "single",
        # clustering_method_columns = "single",
        column_dend_reorder = FALSE,
        show_row_names = FALSE,
        show_column_names = FALSE,
        cluster_row_slices = FALSE,
        cluster_column_slices = FALSE,
        # bottom_annotation   = ha_tme,
        # cluster_rows = row_dend_tumor,
        # cluster_columns = rev(row_dend_tme),
        row_gap = unit(.2, "mm"),
        column_gap = unit(.2, "mm"),
        row_split= row_split_tumor,
        column_split=max(row_split_tme) - row_split_tme + 1,
         column_title_gp = gpar(fontsize = 0, fontface = "bold"),
         row_title_gp = gpar(fontsize = 0, fontface = "bold"),
        width = unit(10, "cm"),
        height= unit(10, "cm"),
    )  #+ ra_tme

hm_both = (hm_cor + hm_tumor ) 
# draw(hm_both, auto_adjust = FALSE)
pdf('output/hm_g2p_corr_genes_2024_03_06.pdf', width =18, height=10)
draw(hm_both, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE, auto_adjust = FALSE)#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_tme_2024_03_06.pdf', width = 10, height = 12)
draw(hm_tme, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE, auto_adjust=FALSE)#, show_heatmap_legend = FALSE) 

dev.off()


library(rstatix)
plasmid_mask$ID = rownames(plasmid_mask)
p_mask = melt(plasmid_mask)
tumor_mask$ID = rownames(tumor_mask)
tme_mask$ID = rownames(tme_mask)
p_mask = merge(p_mask, tumor_mask, by='ID')
p_mask = merge(p_mask, tme_mask, by='ID')
p_mask %<>% rename('variable'= 'var', 'value' = 'val')
p_mask$var = str_replace(p_mask$var, '.plasmid', '')


p_mask$cholangiocytic_bin = factor(p_mask$cholangiocytic_bin )
bxp <- ggboxplot(
  p_mask, x = "var", y = "val", 
  color = "cholangiocytic_bin", palette = c("#00AFBB", "#E7B800")
  )


stat.test <- p_mask %>%
  group_by(var) %>%
  t_test(val ~ cholangiocytic_bin) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj")

library(rstatix)
# Add p-values onto the box plots
stat.test <- stat.test %>%
  add_xy_position(x = "var", dodge = 0.8)
bxp + stat_pvalue_manual(
  stat.test,  label = "p", tip.length = 0
  )

# Add 10% spaces between the p-value labels and the plot border
bxp + stat_pvalue_manual(
  stat.test,  label = "p", tip.length = 0
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) + theme_minimal()



```

```{r}
q_high = 0.95
q_low  = 0.25
adata = anndata::read_h5ad('data_tidy/new_geno_nodule_2024_04_03.h5ad')
# keys_6ROI = c('ML_III_A', 'ML_III_B', 'ML_II_A_1','ML_II_B', 'ML_II_C', 'ML_I_2')
# adata = adata[adata$obs$sample %in% keys_6ROI,]

pdf('output/hm_annots_per_sample_2024_04_03.pdf', width =15, height=10)

for(s in unique(adata$obs$sample)){
    adata_s = adata[adata$obs$sample == s, ]
    adata_s$var$tme_tumor = ifelse(adata_s$var$tme != 'NaN', adata_s$var$tme, ifelse(adata_s$var$tumor != 'NaN', adata_s$var$tumor, 'NaN'))
    tumor_core = adata_s$var_names[adata_s$var$tumor != 'add_on' & adata_s$var$tumor != 'NaN']
    tme_core = adata_s$var_names[adata_s$var$tme != 'add_on' & adata_s$var$tme != 'NaN']
    m  = t(adata_s[['X']])
    # adata_s = adata_s[colSums(m) > quantile(colSums(m), 0.2),]
    # m  = t(adata_s[['X']])
    m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, q_high), 1, ifelse(x < quantile(x, q_low), 0, (x - quantile(x, q_low)) / (quantile(x, q_high) - quantile(x, 0.25))))))
    # m[is.nan(m)] <- 0

    grp_vals     = seq(0, 1, length.out=20)
    grp_cols     = circlize::colorRamp2(grp_vals, pals::ocean.thermal(20))
    adata_s$obsm$plasmid_mask = adata_s$obsm$plasmid_mask[,plasmid_order]
    plasmid_mask = rev(data.frame((adata_s$obsm$plasmid_mask)))
    tumor_mask   = adata_s$obs[, intersect(colnames(adata_s$obs), setdiff(paste0(tumor_order, '_bin'), 'Unclassified_bin'))]
    tme_mask   = adata_s$obs[, paste0(tme_order, '_bin')]
    ha_df      = cbind(tumor_mask, tme_mask, plasmid_mask^10)
    # ha_df      = cbind(plasmid_mask^10)
    ha_cols = c(plasmid_cols, tumor_colors, tme_colors)
    ha_tumor  = HeatmapAnnotation(
            # df = rev(ha_df[colSums(m) != 0,]), 
            df = rev(ha_df),
            col=ha_cols, show_legend=TRUE, 
            gp = gpar(fontsize = 100), 
            # height = unit(5, "cm"), 
            annotation_name_gp= gpar(fontsize = 5), 
            # annotation_height = unit(5, "cm"), 
            simple_anno_size = unit(.25, "cm"),         
            annotation_legend_param = list(direction = "horizontal", at = c(0, 1), labels_gp = gpar(font=1), legend_width = unit(3, "cm"), title_position = "topcenter")
        )



    m = m[rownames(m) %in% adata_s$var_names[adata_s$var$tme_tumor != 'NaN'],]
    m[is.nan(m)] <- 0
    # m = m[,colSums(m) != 0 ]
    split=factor(ifelse(adata_s$var[rownames(m),]['tme'] != 'NaN', 'TME', ifelse(adata_s$var[rownames(m),]['tumor'] != 'NaN', 'Tumor', 'add_on')), levels=c('Tumor', 'TME', 'add_on'))[rowSums(m) != 0]
    m = m[rowSums(m) != 0, ]
    col_dend = dendsort(hclust(dist(plasmid_mask[colnames(m),]^10)))
    # row_dend = as.dendrogram(hclust(as.dist(1- cor(t(m[rownames(m) %in% tumor_core | rownames(m) %in% tme_core,]), method='spearman'))))


    df_tumor = adata_s$var[adata_s$var$tumor != 'NaN',]['tumor']
    tumor_genes = rownames(df_tumor)[rownames(df_tumor) %in% rownames(m)]
    df_tumor = df_tumor[tumor_genes,]
    names(df_tumor) = tumor_genes
    df_tumor =  as.character(df_tumor)
    names(df_tumor) = tumor_genes
    row_dend_tumor = hclust(as.dist(1- cor(t(m[tumor_genes,]), method='pearson')))
    row_split_tumor = cutree(row_dend_tumor, k= 6)
    row_split_tumor = (max(row_split_tumor)+1) - row_split_tumor %>% map(~max(match(df_tumor[names(which(row_split_tumor == .x))], tumor_genes_order))) %>% unlist()
    # max(match(df_tumor[names(which(row_split_tumor == 2))], tumor_order))
    # tumor_core = names(df_tumor) = rownames(m)[rownames(m) %in% tumor_core]
    # ra_tumor = Heatmap(df_tumor, name='signature', width = unit(0.5, "cm"), column_names_gp=gpar(fontsize = 0), row_names_gp=gpar(fontsize = 7.5), col= celltype_cols, show_row_names =TRUE)
    ra_tumor = rowAnnotation(Tumor=df_tumor,col= list(Tumor=celltype_cols_static[as.character(unique(df_tumor))]), annotation_name_gp= gpar(fontsize = 0))
    set.seed(1375)
    # column_order = order(factor(adata_s[colnames(m),]$obs[,'dom_type'], ordered=TRUE, levels = c(tumor_order, 'add_on')))
    # col_split =  factor(adata_s[colnames(m),]$obs[,'dom_tumor'], ordered=TRUE, levels = rev(tumor_order))
    hm_tumor = Heatmap(
            m[tumor_genes,]^2, 
            cluster_columns = col_dend,
            # row_split=row_split_tumor, 
            # column_split = factor(abv_types[as.character(col_split)], ordered=TRUE, levels=rev(abv_types)), 
            # row_order = names(sort(df_tumor, decreasing=FALSE)),
            # column_order = column_order,
            row_title_gp = gpar(fontsize = 0),
            # row_dend_reorder = FALSE,
            row_names_gp=gpar(fontsize = 7.5),
            row_gap = unit(.2, "mm"),
            column_gap = unit(.2, "mm"),
            left_annotation = ra_tumor,
            # cluster_row_slices = FALSE,
            # cluster_columns = col_dend,
            # cluster_row_slices = FALSE,
            cluster_column_slices = FALSE,
            # clustering_distance_rows = 'spearman',
            # show_row_names =FALSE,
            # show_column_dend = FALSE,
            column_names_side='top',
            row_names_side = 'left',
            column_names_gp=gpar(fontsize = 5),
            name="Scaled\nGene Expression", #column_title = region,  
            # column_title_gp = gpar(fontsize = 7.5, rot=0), 
            # column_title_rot = 0,
            top_annotation =ha_tumor, col=grp_cols,
            cluster_row_slices = FALSE,
            show_column_dend = FALSE,
            show_row_dend = FALSE,
            width = unit(15, "cm"),
            height= unit(10, "cm"),
            row_names_centered = TRUE,
            column_title=s,
            column_title_gp = gpar(fontsize = 10, fontface = "bold"),

            
        )  # + ra_tumor
        draw(hm_tumor, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE, show_heatmap_legend = FALSE) 

}

dev.off()

# lgd_tumor = Legend(labels = setdiff(unique(adata$var$tumor), c('NaN', 'add_on')), title = "TME", legend_gp = gpar(col = celltype_cols_static),
#     title_position = "leftcenter-rot")

df_tme = adata$var[adata$var$tme != 'NaN',]['tme']
tme_genes = rownames(df_tme)[rownames(df_tme) %in% rownames(m)]
tme_genes = setdiff(tme_genes, 'Postn')
df_tme = df_tme[tme_genes,]
names(df_tme) = tme_genes
# tme_core = names(df_tme) = rownames(m)[rownames(m) %in% tme_core]
# ra_tme = Heatmap(df_tme, name='signature', width = unit(0.5, "cm"), row_names_gp=gpar(fontsize = 7.5), col= celltype_cols_static, show_row_names =TRUE)
set.seed(1375)
row_dend_tme = hclust(as.dist(1- cor(t(m[tme_genes,]), method='pearson')))
row_split_tme = cutree(row_dend_tme, k= 10)
row_split_tme = (max(row_split_tme)+1) - (row_split_tme %>% map(~max(match(df_tme[names(which(row_split_tme == .x))], rev(tme_genes_order)))) %>% unlist())
ra_tme = rowAnnotation(TME=df_tme,col= list(TME=celltype_cols_static[as.character(unique(df_tme))]), annotation_name_gp= gpar(fontsize = 0))
# m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, q_high), 1, ifelse(x < quantile(x, q_low), 0, (x - quantile(x, q_low)) / (quantile(x, q_high) - quantile(x, 0.25))))))
# row_dend_tme = hclust(as.dist(1- cor(t(m[tme_genes,]^2), method='pearson')))
# row_split = cutree(row_dend_tme , k = 10)
# row_order = 

m2  = t(adata$layers[['quantiles']])
m2  = m2[, colnames(m)]
m2  = t(apply(m2, 1, function(x) ifelse(x > quantile(x, q_high), 1, ifelse(x < quantile(x, q_low), 0, (x - quantile(x, q_low)) / (quantile(x, q_high) - quantile(x, 0.25))))))
m2[is.nan(m2)] <- 0
ha_tme        = HeatmapAnnotation(df = rev(ha_df), col=ha_cols, show_legend=FALSE, gp = gpar(fontsize = 100), height = unit(1, "cm"), annotation_name_gp= gpar(fontsize = 2), annotation_height = unit(1, "cm"), simple_anno_size = unit(.1, "cm"))
col_split = ifelse(col_split == 'Normal', 'Normal', 'Tumor')
hm_tme = Heatmap(
        m2[tme_genes,]^2, 
        row_split=row_split_tme, 
        column_split = factor(col_split, ordered=TRUE, levels=c('Tumor', 'Normal')),
        # column_split = factor(abv_types[as.character(col_split)], ordered=TRUE, levels=abv_types), 
        # row_km_repeats = 10000,
        row_title_gp = gpar(fontsize = 0),
        # row_order = names(sort(df_tme, decreasing=TRUE)),
        column_dend_reorder = FALSE,
        row_names_gp=gpar(fontsize = 7.5),
        row_gap = unit(.2, "mm"),
        column_gap = unit(.2, "mm"),
        # cluster_columns = col_dend,
        # cluster_row_slices = FALSE,
        # clustering_distance_rows = 'spearman',
        left_annotation = ra_tme,
        cluster_column_slices=FALSE,
        cluster_row_slices = FALSE,
        # show_row_names =FALSE,
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        column_names_gp=gpar(fontsize = 0),
        name="Scaled\nGene Expression",# column_title = region,  
        column_title_gp = gpar(fontsize = 10), 
        # cluster_row_slices = FALSE,
        column_title_rot = 0,
        col=grp_cols,
        top_annotation =ha_tme,
        # cluster_rows = as.dendrogram(row_dend_tme), 
        height = unit(10, "cm"),
        width = unit(15, "cm"),
        row_names_centered = TRUE,
        row_names_side = 'left'
        annotation_legend_param = list(title_position ='leftcenter-rot'),

    )  #+ ra_tme 


hm_all = (hm_tumor %v% hm_tme)


pdf('output/test.pdf', width =20, height=20)
draw(hm_tumor, padding = unit(c(20, 25, 10, 25), "mm"))#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_total_nodules_local_tumor_only_2024_02_22.pdf', width =20, height=9)
draw(hm_tumor, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE)#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_total_nodules_local_tme_only_2024_02_22.pdf', width =20, height=9)
draw(hm_tme, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE)#, show_heatmap_legend = FALSE) 

dev.off()
    # cat('\n\n')

ra_celltype = rowAnnotation(celltype=c(df_tumor, df_tme),col= list(celltype=celltype_cols_static[as.character(c(unique(df_tumor), unique(df_tme)))]), annotation_name_gp= gpar(fontsize = 0))
grp_vals_cor     = seq(-1, 1, length.out=15)
grp_cols_cor     = circlize::colorRamp2(grp_vals_cor, pals::ocean.curl(15))

ha_tme = HeatmapAnnotation(TME=df_tme,col= list(TME=celltype_cols_static[as.character(unique(df_tme))]), annotation_name_gp= gpar(fontsize = 0))
hm_cor = Heatmap(
        cor(t(m[names(c(df_tumor)),]), t(m2[names(c(df_tme)),])), #), method='spearman'), 
        # right_annotation = ra_tumor,
        name="Pearson's \ncor. coefficient", #column_title = region,  
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        col=grp_cols_cor,
        # clustering_method_rows = "single",
        # clustering_method_columns = "single",
        column_dend_reorder = FALSE,
        show_row_names = FALSE,
        show_column_names = FALSE,
        cluster_row_slices = FALSE,
        cluster_column_slices = FALSE,
        # bottom_annotation   = ha_tme,
        # cluster_rows = row_dend_tumor,
        # cluster_columns = rev(row_dend_tme),
        row_gap = unit(.2, "mm"),
        column_gap = unit(.2, "mm"),
        row_split= row_split_tumor,
        column_split=max(row_split_tme) - row_split_tme + 1,
         column_title_gp = gpar(fontsize = 0, fontface = "bold"),
         row_title_gp = gpar(fontsize = 0, fontface = "bold"),
        width = unit(10, "cm"),
        height= unit(10, "cm"),
    )  #+ ra_tme

hm_both = (hm_cor + hm_tumor ) 
# draw(hm_both, auto_adjust = FALSE)
pdf('output/hm_g2p_corr_genes_2024_03_06.pdf', width =18, height=10)
draw(hm_both, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE, auto_adjust = FALSE)#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_tme_2024_03_06.pdf', width = 10, height = 12)
draw(hm_tme, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE, auto_adjust=FALSE)#, show_heatmap_legend = FALSE) 

dev.off()


library(rstatix)
plasmid_mask$ID = rownames(plasmid_mask)
p_mask = melt(plasmid_mask)
tumor_mask$ID = rownames(tumor_mask)
tme_mask$ID = rownames(tme_mask)
p_mask = merge(p_mask, tumor_mask, by='ID')
p_mask = merge(p_mask, tme_mask, by='ID')
p_mask %<>% rename('variable'= 'var', 'value' = 'val')
p_mask$var = str_replace(p_mask$var, '.plasmid', '')


p_mask$cholangiocytic_bin = factor(p_mask$cholangiocytic_bin )
bxp <- ggboxplot(
  p_mask, x = "var", y = "val", 
  color = "cholangiocytic_bin", palette = c("#00AFBB", "#E7B800")
  )


stat.test <- p_mask %>%
  group_by(var) %>%
  t_test(val ~ cholangiocytic_bin) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj")

library(rstatix)
# Add p-values onto the box plots
stat.test <- stat.test %>%
  add_xy_position(x = "var", dodge = 0.8)
bxp + stat_pvalue_manual(
  stat.test,  label = "p", tip.length = 0
  )

# Add 10% spaces between the p-value labels and the plot border
bxp + stat_pvalue_manual(
  stat.test,  label = "p", tip.length = 0
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) + theme_minimal()



```



```{r}
q_high = 0.95
q_low  = 0.25
adata = anndata::read_h5ad('data_tidy/new_geno_nodule_2024_04_03.h5ad')
# keys_6ROI = c('ML_III_A', 'ML_III_B', 'ML_II_A_1','ML_II_B', 'ML_II_C', 'ML_I_2')
# adata = adata[adata$obs$sample %in% keys_6ROI,]
adata$var$tme_tumor = ifelse(adata$var$tme != 'NaN', adata$var$tme, ifelse(adata$var$tumor != 'NaN', adata$var$tumor, 'NaN'))
tumor_core = adata$var_names[adata$var$tumor != 'add_on' & adata$var$tumor != 'NaN']
tme_core = adata$var_names[adata$var$tme != 'add_on' & adata$var$tme != 'NaN']
m  = t(adata[['X']])
adata = adata[colSums(m) > quantile(colSums(m), 0.2),]
m  = t(adata[['X']])
m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, q_high), 1, ifelse(x < quantile(x, q_low), 0, (x - quantile(x, q_low)) / (quantile(x, q_high) - quantile(x, 0.25))))))
m[is.nan(m)] <- 0

grp_vals     = seq(0, 1, length.out=20)
grp_cols     = circlize::colorRamp2(grp_vals, pals::ocean.thermal(20))
plasmid_mask = rev(data.frame((adata$obsm$plasmid_mask)))
# tumor_mask   = adata$obs[, setdiff(paste0(tumor_order, '_bin'), 'Unclassified_bin')]
tumor_mask   = adata$obs[, intersect(paste0(tumor_order, '_bin'), colnames(adata$obs))]
tme_mask   = adata$obs[, paste0(tme_order, '_bin')]
ha_df      = cbind(plasmid_mask^10, tumor_mask, tme_mask)
# ha_df      = cbind(plasmid_mask^10)
ha_cols = c(plasmid_cols, tumor_colors, tme_colors)
ha_tumor         = HeatmapAnnotation(df = ha_df[colSums(m) != 0,], col=ha_cols, show_legend=FALSE, gp = gpar(fontsize = 100), height = unit(5, "cm"), annotation_name_gp= gpar(fontsize = 7.5), annotation_height = unit(5, "cm"), simple_anno_size = unit(.25, "cm"))
ha_tme         = HeatmapAnnotation(df = rev(ha_df[colSums(m) != 0,]), col=ha_cols, show_legend=FALSE, gp = gpar(fontsize = 100), height = unit(5, "cm"), annotation_name_gp= gpar(fontsize = 7.5), annotation_height = unit(5, "cm"), simple_anno_size = unit(.25, "cm"))

m = m[rownames(m) %in% adata$var_names[adata$var$tme_tumor != 'NaN'],]
m[is.nan(m)] <- 0
m = m[,colSums(m) != 0 ]
split=factor(ifelse(adata$var[rownames(m),]['tme'] != 'NaN', 'TME', ifelse(adata$var[rownames(m),]['tumor'] != 'NaN', 'Tumor', 'add_on')), levels=c('Tumor', 'TME', 'add_on'))[rowSums(m) != 0]
m = m[rowSums(m) != 0, ]
# col_dend = dendsort(hclust(dist(plasmid_mask[colnames(m),]^5)))
# row_dend = as.dendrogram(hclust(as.dist(1- cor(t(m[rownames(m) %in% tumor_core | rownames(m) %in% tme_core,]), method='spearman'))))


df_tumor = adata$var[adata$var$tumor != 'NaN',]['tumor']
tumor_genes = rownames(df_tumor)[rownames(df_tumor) %in% rownames(m)]
tumor_genes = setdiff(tumor_genes, 'Vil1')
df_tumor = df_tumor[tumor_genes,]
names(df_tumor) = tumor_genes
row_dend_tumor = hclust(as.dist(1- cor(t(m[tumor_genes,]), method='pearson')))
row_split_tumor = cutree(row_dend_tumor, k= 6)
row_split_tumor = (max(row_split_tumor)+1) - row_split_tumor %>% map(~max(match(df_tumor[names(which(row_split_tumor == .x))], tumor_genes_order))) %>% unlist()
# tumor_core = names(df_tumor) = rownames(m)[rownames(m) %in% tumor_core]
# ra_tumor = Heatmap(df_tumor, name='signature', width = unit(0.5, "cm"), column_names_gp=gpar(fontsize = 0), row_names_gp=gpar(fontsize = 7.5), col= celltype_cols, show_row_names =TRUE)
ra_tumor = rowAnnotation(Tumor=df_tumor,col= list(Tumor=celltype_cols_static[as.character(unique(df_tumor))]), annotation_name_gp= gpar(fontsize = 0))
set.seed(1375)
# column_order = order(factor(adata[colnames(m),]$obs[,'dom_type'], ordered=TRUE, levels = c(tumor_order, 'add_on')))
# col_split =  factor(adata[colnames(m),]$obs[,'dom_tumor'], ordered=TRUE, levels = tumor_order)
col_split =  factor(adata[colnames(m),]$obs[,'dom_tumor'], ordered=TRUE, levels = tumor_order)
col_split = ifelse(col_split == 'Normal', 'Normal', 'Tumor')
hm_tumor = Heatmap(
        m[tumor_genes,]^2, 
        cluster_rows = row_dend_tumor,
        # row_split=6, 
        # row_split=row_split_tumor, 
        column_split = col_split,
        # row_order = names(sort(df_tumor, decreasing=FALSE)),
        # column_order = column_order,
        row_title_gp = gpar(fontsize = 0),
        # row_dend_reorder = FALSE,
        row_names_gp=gpar(fontsize = 7.5),
        row_gap = unit(.2, "mm"),
        column_gap = unit(5, "mm"),
        left_annotation = ra_tumor,
        # cluster_row_slices = FALSE,
        # cluster_columns = col_dend,
        # cluster_row_slices = FALSE,
        cluster_column_slices = FALSE,
        # clustering_distance_rows = 'spearman',
        # show_row_names =FALSE,
        # show_column_dend = FALSE,
        column_names_side='top',
        row_names_side = 'left',
        column_names_gp=gpar(fontsize = 3),
        name="Scaled\nGene Expression", #column_title = region,  
        # column_title_gp = gpar(fontsize = 7.5, rot=0), 
        # column_title_rot = 0,
        top_annotation =ha_tumor, col=grp_cols,
        cluster_row_slices = FALSE,
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        width = unit(50, "cm"),
        height= unit(8, "cm"),
        row_names_centered = TRUE,
        column_title='',
        column_title_gp = gpar(fontsize = 20, fontface = "bold"),

        
        )  # + ra_tumor

# lgd_tumor = Legend(labels = setdiff(unique(adata$var$tumor), c('NaN', 'add_on')), title = "TME", legend_gp = gpar(col = celltype_cols_static),
#     title_position = "leftcenter-rot")

df_tme = adata$var[adata$var$tme != 'NaN',]['tme']
tme_genes = rownames(df_tme)[rownames(df_tme) %in% rownames(m)]
tme_genes = setdiff(tme_genes, 'Postn')
df_tme = df_tme[tme_genes,]
names(df_tme) = tme_genes
# tme_core = names(df_tme) = rownames(m)[rownames(m) %in% tme_core]
# ra_tme = Heatmap(df_tme, name='signature', width = unit(0.5, "cm"), row_names_gp=gpar(fontsize = 7.5), col= celltype_cols_static, show_row_names =TRUE)
ra_tme = rowAnnotation(TME=df_tme,col= list(TME=celltype_cols_static[as.character(unique(df_tme))]), annotation_name_gp= gpar(fontsize = 0))
set.seed(1375)
# m  = t(apply(m, 1, function(x) ifelse(x > quantile(x, q_high), 1, ifelse(x < quantile(x, q_low), 0, (x - quantile(x, q_low)) / (quantile(x, q_high) - quantile(x, 0.25))))))
row_dend_tme = hclust(as.dist(1- cor(t(m[tme_genes,]^2), method='pearson')))
row_split = cutree(row_dend_tme , k = 9)
# row_order = 
hm_tme = Heatmap(
        m[tme_genes,]^2, 
        # row_split=7, 
        # column_split = col_split,
        # row_km_repeats = 10000,
        row_title_gp = gpar(fontsize = 0),
        # row_order = names(sort(df_tme, decreasing=TRUE)),
        column_dend_reorder = TRUE,
        row_names_gp=gpar(fontsize = 7.5),
        row_gap = unit(.2, "mm"),
        column_gap = unit(5, "mm"),
        # cluster_columns = col_dend,
        # cluster_row_slices = FALSE,
        cluster_column_slices = FALSE,
        clustering_distance_rows = 'spearman',
        left_annotation = ra_tme,
        row_names_side = 'left',
        # show_row_names =FALSE,
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        column_names_gp=gpar(fontsize = 0),
        name="Scaled\nGene Expression",# column_title = region,  
        column_title_gp = gpar(fontsize = 7.5, fontface = "bold"), 
        # cluster_row_slices = FALSE,
        column_title_rot = 45,
        col=grp_cols,
        # top_annotation =ha_tme,
        cluster_rows = as.dendrogram(row_dend_tme),
        height = unit(8, "cm"),
        width = unit(50, "cm"),
        row_names_centered = TRUE,

    )  #+ ra_tme 


hm_all = (hm_tumor %v% hm_tme)


pdf('output/hm_g2p_all_noduels_2024_04_03.pdf', width =25, height=22)
draw(hm_all, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE) 

dev.off()


pdf('output/hm_g2p_total_nodules_local_tumor_only_2024_02_22.pdf', width =20, height=9)
draw(hm_tumor, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE)#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_total_nodules_local_tme_only_2024_02_22.pdf', width =20, height=9)
draw(hm_tme, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE)#, show_heatmap_legend = FALSE) 

dev.off()
    # cat('\n\n')

ra_celltype = rowAnnotation(celltype=c(df_tumor, df_tme),col= list(celltype=celltype_cols_static[as.character(c(unique(df_tumor), unique(df_tme)))]), annotation_name_gp= gpar(fontsize = 0))
grp_vals_cor     = seq(-1, 1, length.out=15)
grp_cols_cor     = circlize::colorRamp2(grp_vals_cor, pals::ocean.curl(15))

ha_tme = HeatmapAnnotation(TME=df_tme,col= list(TME=celltype_cols_static[as.character(unique(df_tme))]), annotation_name_gp= gpar(fontsize = 0))
hm_cor = Heatmap(
        cor(t(m[names(c(df_tumor)),]), t(m[names(c(df_tme)),])), #), method='spearman'), 
        # right_annotation = ra_tumor,
        name="Pearson's \ncor. coefficient", #column_title = region,  
        show_column_dend = FALSE,
        show_row_dend = FALSE,
        col=grp_cols_cor,
        # clustering_method_rows = "single",
        cluster_rows = as.dendrogram(row_dend_tumor),
        # clustering_method_columns = "single",
        column_dend_reorder = FALSE,
        show_row_names = FALSE,
        show_column_names = FALSE,
        # bottom_annotation   = ha_tme,
        cluster_columns = rev(as.dendrogram(row_dend_tme)),
        row_split= 6,
        column_split=7,
         column_title_gp = gpar(fontsize = 0, fontface = "bold"),
         row_title_gp = gpar(fontsize = 0, fontface = "bold"),
        width = unit(10, "cm"),
        height= unit(10, "cm"),
    )  #+ ra_tme

hm_both = (hm_cor + hm_tumor ) 
# draw(hm_both, auto_adjust = FALSE)
pdf('output/hm_g2p_corr_genes_2024_02_28.pdf', width =18, height=10)
draw(hm_both, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE, auto_adjust = FALSE)#, show_heatmap_legend = FALSE) 

dev.off()


pdf('output/hm_g2p_tme_2024_02_28.pdf', width = 10, height = 12)
draw(hm_tme, padding = unit(c(20, 25, 10, 25), "mm"), merge_legend = TRUE, auto_adjust=FALSE)#, show_heatmap_legend = FALSE) 

dev.off()



```
